-- Generated by scripts/backfill_risp_flags.mjs
begin;
update public.plate_appearances
set runner_on_first_before = false,
    runner_on_second_before = false,
    runner_on_third_before = false
where id in (3491, 3493, 3495, 3497, 3505, 3506, 3507, 3501, 3502, 3503, 3508, 3509, 3510, 3504, 3492, 3494, 3496, 3498, 3500, 3511, 3512, 3513, 3514, 3516, 3518, 3527, 3529, 3531, 3522, 3523, 3524, 3525, 3515, 3533, 3535, 3537, 3517, 3519, 3521, 3539, 3540, 3528, 3530, 3532, 3534, 3536, 3541, 3544, 3546, 3560, 3562, 3564, 3566, 3552, 3556, 3558, 3570, 3547, 3549, 3551, 3576, 3561, 3563, 3553, 3555, 3565, 3567, 3578, 3580, 3584, 3586, 3595, 3597, 3599, 3588, 3590, 3594, 3601, 3602, 3603, 3583, 3585, 3587, 3589, 3591, 3593, 3596, 3598, 3600, 3607, 3608, 3609, 3610, 3616, 3618, 3620, 3621, 3611, 3612, 3613, 3614, 3622, 3623, 3624, 3626, 3617, 3619, 3627, 3640, 3642, 3644, 3646, 3648, 3636, 3637, 3638, 3639, 3649, 3650, 3651, 3628, 3630, 3652, 3641, 3643, 3645, 3647, 3653, 3654, 3655, 3656, 3661, 3662, 3657, 3664, 3665, 3666, 3667, 3668, 3669, 3670, 3673, 3676, 3691, 3693, 3695, 3679, 3681, 3683, 3685, 3697, 3699, 3701, 3703, 3705, 3671, 3674, 3677, 3707, 3692, 3694, 3680, 3682, 3684, 3686, 3688, 3690, 3672, 3675, 3696, 3698, 3700, 3702, 3704, 3708, 3719, 3720, 3721, 3713, 3714, 3722, 3723, 3724, 3718, 3728, 3730, 3741, 3743, 3745, 3736, 3737, 3738, 3739, 3747, 3749, 3731, 3733, 3755, 3756, 3742);
update public.plate_appearances
set runner_on_first_before = false,
    runner_on_second_before = false,
    runner_on_third_before = false
where id in (3744, 3746, 3748);
update public.plate_appearances
set runner_on_first_before = false,
    runner_on_second_before = true,
    runner_on_third_before = false
where id in (3499, 3573, 3575, 3579, 3604, 3605, 3606, 3632, 3634, 3678, 3711);
update public.plate_appearances
set runner_on_first_before = true,
    runner_on_second_before = false,
    runner_on_third_before = false
where id in (3520, 3526, 3538, 3548, 3568, 3554, 3542, 3572, 3574, 3557, 3569, 3571, 3582, 3592, 3615, 3629, 3663, 3658, 3659, 3660, 3687, 3689, 3706, 3710, 3712, 3715, 3709, 3725, 3726, 3727, 3732, 3734, 3740, 3751, 3753, 3735, 3750, 3752);
update public.plate_appearances
set runner_on_first_before = true,
    runner_on_second_before = true,
    runner_on_third_before = false
where id in (3550, 3545, 3559, 3543, 3577, 3631, 3633, 3635, 3716, 3717, 3729, 3754);
update public.plate_appearances
set runner_on_first_before = true,
    runner_on_second_before = false,
    runner_on_third_before = true
where id in (3581);
update public.plate_appearances
set runner_on_first_before = false,
    runner_on_second_before = false,
    runner_on_third_before = true
where id in (3625);
update public.season_plate_appearances
set runner_on_first_before = false,
    runner_on_second_before = false,
    runner_on_third_before = false
where id in (952, 954, 955, 957, 959, 961, 964, 966, 970, 972, 978, 979, 986, 992, 999, 1039, 1041, 1211, 1069, 1071, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1082, 1083, 1084, 1085, 1086, 1092, 1093, 1094, 1095, 1097, 1098, 1099, 1101, 1102, 1103, 1104, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 891, 895, 896, 897, 898, 899, 900, 901, 902, 905, 907, 908, 909, 910, 911, 915, 916, 917, 918, 921, 922, 923, 924, 929, 930, 931, 932, 933, 934, 938, 939, 940, 946, 947, 948, 949, 950, 965, 967, 968, 969, 973, 974, 975, 976, 977, 987, 994, 1000, 795, 800, 801, 802, 803, 804, 807, 808, 809, 810, 811, 812, 813, 814, 815, 1032, 1033, 1034, 1035, 1036, 1037, 1040, 1042, 1043, 1044, 1045, 1046, 1050, 1051, 1052, 1053, 1056, 1059, 1060, 1065, 816, 817, 818, 819, 820, 821, 822, 824, 825, 826, 829, 830, 831, 832, 833, 834, 836, 837, 1003, 1005, 1006, 1007, 1010, 1011, 1012, 1013, 1014, 1017, 1018, 1019, 1021, 1022, 1025, 1026, 1027, 1029, 1030, 1031, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 875, 876, 879, 880, 881, 882, 883, 884, 885, 842);
update public.season_plate_appearances
set runner_on_first_before = false,
    runner_on_second_before = false,
    runner_on_third_before = false
where id in (843, 844, 846, 847, 848, 850, 851, 852, 854, 855, 859, 861);
update public.season_plate_appearances
set runner_on_first_before = true,
    runner_on_second_before = false,
    runner_on_third_before = false
where id in (988, 989, 1001, 1072, 1080, 1081, 1087, 1090, 1091, 1096, 1100, 1105, 892, 893, 903, 904, 906, 912, 913, 919, 920, 925, 926, 927, 928, 935, 962, 971, 991, 993, 995, 996, 998, 796, 797, 798, 799, 805, 806, 1038, 1054, 1058, 1061, 1066, 823, 827, 835, 838, 839, 1004, 1024, 1028, 874, 877, 878, 845, 853, 858, 862, 863);
update public.season_plate_appearances
set runner_on_first_before = true,
    runner_on_second_before = true,
    runner_on_third_before = false
where id in (1002, 1106, 1107, 1108, 1109, 963, 1067, 1068, 1070, 828);
update public.season_plate_appearances
set runner_on_first_before = false,
    runner_on_second_before = true,
    runner_on_third_before = true
where id in (1088, 914, 1062);
update public.season_plate_appearances
set runner_on_first_before = true,
    runner_on_second_before = false,
    runner_on_third_before = true
where id in (1089, 1048, 1049);
update public.season_plate_appearances
set runner_on_first_before = false,
    runner_on_second_before = true,
    runner_on_third_before = false
where id in (936, 937, 958, 960, 990, 1047, 1063, 1064, 1015, 1016, 1023, 849, 856, 857);
commit;
