// Plain-English descriptions for stat abbreviations that aren't self-explanatory from their
// name alone (BABIP, wOBA, etc.). Simple counting stats (H, HR, RBI, W, SV...) are intentionally
// left out — surfacing a tooltip for "HR" would just be noise. Keyed by the exact column label
// text as it's rendered in table headers across the app, so this list doubles as an inventory of
// every advanced stat header currently in use.
export const STAT_DESCRIPTIONS = {
  'Exp. WAR': 'Experimental combined value: position-player WAR plus pitching WAR using the FanGraphs framework. Missing inputs are neutral assumptions; inspect coverage.',
  'Position WAR': 'Batting, baserunning, fielding, position, league, and replacement runs divided by runs per win. Includes batting value earned by pitchers.',
  'Pitching WAR': 'FanGraphs-style pitching value from home runs, walks, hit batters, strikeouts, and infield flies, with replacement and league corrections.',
  'Legacy WAR': 'Older simplified batting/fielding estimate with fixed constants and no pitching component. Use Experimental WAR in Stats for the combined version.',
  'Bat Runs': 'Weighted batting runs above the competition average using published 2025 MLB weights and wOBA scale.',
  BsR: 'Experimental baserunning runs from extra-base opportunities and double-play avoidance. A dash means unmeasured.',
  'Fld Runs': 'Experimental fielding runs from tracked outs above average, arm outcomes, and attributed double plays.',
  'Pos Adj': 'FanGraphs positional run adjustment, prorated by recorded defensive innings at each position.',
  'Lg Adj': 'League correction that centers position-player runs above average at zero.',
  'Repl Runs': 'Position-player replacement credit allocated by plate appearances using the MLB replacement budget.',
  BatUVA: 'Batting User Value Added in runs: modeled swing/take, swing-mode, timing, and contact execution value attributable to human inputs. A dash means the required input model is unavailable, not zero.',
  SwDec: 'Swing Decision Runs: modeled value of the user choosing to swing, take, bunt, or use a Star Swing in that pitch context.',
  ConEx: 'Contact Execution Runs: expected contact value above or below the same character and swing-mode baseline, before defense and stadium outcomes.',
  PitchUVA: 'Pitching User Value Added in runs from modeled pitch selection, aim, charge, and execution. Character pitch shape and velocity remain outside the user total.',
  PitchSel: 'Pitch Selection Runs: modeled value of the user selecting normal, changeup, charge, or Star Pitch in context.',
  'Cmd/Exec': 'Pitch command and execution runs above the same character and selected-pitch baseline.',
  BsRUVA: 'Baserunning User Value Added in runs from shake/sprint execution. Automatic advance/hold choices are excluded.',
  RunEx: 'Run Execution Runs: change in expected advancement value caused by measured shake effort versus the same character baseline.',
  FldUVA: 'Fielding User Value Added in runs from explicit sprint, dive, jump, Buddy, and gimmick-avoidance actions. Automatic selection and routes are excluded.',
  'Action Dec': 'Fielding action decision runs from choosing an explicit user-controlled action over the best ordinary alternative.',
  'Action Ex': 'Fielding action execution runs from the timing/result of an explicit action versus its contextual baseline.',
  'Auto BR Runs': 'Modeled extra-base value produced by automatic advance/hold behavior. Context only: it is deliberately excluded from BsRUVA.',
  'Auto BR Opp': 'Automatic runner opportunities with modeled run value.',
  'Input Tracked%': 'Share of pitches with an explicitly observed normal/changeup/star input. A movement-based fastball/curveball label alone does not prove the input.',
  'Aim Tracked%': 'Share of pitches with an absolute plate endpoint or aim target available to the command model.',
  'Charge Tracked%': 'Share of pitches with explicit pitch-charge evidence.',
  'Mode Tracked%': 'Share of swings explicitly identified as slap or charge. Swing animation frames alone are not treated as charge evidence.',
  'Chase%': 'Swings at pitches confidently outside the strike zone divided by pitches confidently outside the zone, matching the MLB/Statcast chase-rate concept. Edge pitches are excluded.',
  'Chase Contact%': 'Chase swings that made contact divided by all recorded chase swings.',
  'Out-Zone Pitches': 'Pitches confidently outside the strike zone. Taken balls count directly; swung pitches require measured plate location outside the conservative edge.',
  'Zone Swing%': 'Swings at pitches confidently inside the strike zone divided by pitches confidently inside the zone.',
  'Zone Tracked%': 'Share of pitches classified confidently inside or outside the zone. Shadow-edge and missing-location pitches remain unclassified.',
  'Shadow Pitches': 'Pitches in the character-sensitive plate-edge band where called-ball and called-strike calibration samples overlap; excluded from Chase% and Zone Swing%.',
  'Slap Swings': 'Ordinary swings explicitly classified from controller input as uncharged slap swings. Unknown ordinary swings are not counted.',
  'Charge Swings': 'Ordinary swings explicitly classified from controller input as charged swings. Swing animation duration alone is not accepted as charge evidence.',
  'Shake Tracked%': 'Share of qualifying runs with the shake input itself observed; measured runner speed alone is not an input flag.',
  'Star Choices': 'Plate appearances on which the user selected a Star Swing.',
  'Buddy Contact%': 'Buddy Attacks that made contact divided by recorded Buddy Attack attempts.',
  Actions: 'Recorded user-controlled fielding action attempts included in the UVA evidence layer.',
  'Object Clears': 'Recorded Buddy Attacks that intentionally cleared or broke a field gimmick.',
  // Rate/slash stats
  AVG: 'Batting average: hits divided by at-bats.',
  OBP: 'On-base percentage: how often a batter reaches base via hit, walk, or hit-by-pitch.',
  SLG: 'Slugging percentage: total bases divided by at-bats.',
  OPS: 'On-base plus slugging: OBP + SLG combined into one number.',
  'OPS+': 'OPS adjusted to league average, where 100 is average and higher is better.',
  ISO: 'Isolated power: SLG minus AVG, measuring extra-base power on its own.',
  BABIP: 'Batting average on balls in play, excluding strikeouts and home runs.',
  'BABIP Allowed': 'Batting average allowed on balls in play, excluding strikeouts and home runs.',
  wOBA: 'Weighted on-base average: values every offensive outcome (walk, single, homer, etc.) by how much it actually contributes to scoring runs.',
  xwOBA: 'Expected wOBA based on quality of contact (exit velocity, launch angle) rather than actual results.',
  'wRC+': 'Weighted runs created, adjusted to league average, where 100 is average and higher is better.',
  RC: 'Runs Created: an estimate of how many runs a player generated with their offense.',
  'RC/3': 'Runs Created per 3-inning game (9 outs).',
  xBA: 'Expected batting average based on quality of contact rather than actual results.',
  xSLG: 'Expected slugging percentage based on quality of contact rather than actual results.',
  xBAA: 'Expected batting average allowed, modeled from the quality of contact against this pitcher.',
  xSLGA: 'Expected slugging percentage allowed, modeled from the quality of contact against this pitcher.',
  xwOBAA: 'Expected wOBA allowed, modeled from the quality of contact against this pitcher.',
  'AVG -xBA': 'Actual batting average minus expected (xBA). Positive means more hits fell in than the contact deserved.',
  'SLG -xSLG': 'Actual slugging minus expected (xSLG). Positive means the results outran the contact quality.',
  'wOBA -xwOBA': 'Actual wOBA minus expected (xwOBA). Positive means the results outran the contact quality.',

  // Rate stats — plate discipline
  'K%': 'Strikeouts divided by plate appearances.',
  'BB%': 'Walks divided by plate appearances.',
  'BB/K': 'Walk-to-strikeout ratio.',
  'K/BB': 'Strikeout-to-walk ratio.',
  'XBH%': 'Extra-base hits (2B, 3B, HR) divided by hits.',
  'HR/PA': 'Home runs divided by plate appearances.',
  'P/PA': 'Average pitches seen per plate appearance.',
  'Whiff%': 'Percentage of swings that missed the ball entirely.',
  'Foul%': 'Percentage of pitches fouled off.',
  'KS%': 'Percentage of strikeouts that were swinging (as opposed to looking).',
  'KL%': 'Percentage of strikeouts that were looking (as opposed to swinging).',

  // Pitching rate stats
  'ERA/3': 'Earned Run Average per 3-inning game (9 outs).',
  FIP: 'Fielding Independent Pitching: estimates ERA using only outcomes a pitcher directly controls (K, BB, HR), scaled to the 3-inning environment.',
  'FIP-': 'FIP relative to league average, where lower than 100 is better.',
  'ERA-': 'ERA/3 relative to league average, where lower than 100 is better.',
  WHIP: 'Walks plus hits allowed, per inning pitched.',
  'K/3': 'Strikeouts per 3-inning game (9 outs).',
  'BB/3': 'Walks per 3-inning game (9 outs).',
  'H/3': 'Hits allowed per 3-inning game (9 outs).',
  'HR/3': 'Home runs allowed per 3-inning game (9 outs).',
  'Star Pitch %': 'Percentage of pitches thrown that were the pitcher\'s Star Pitch.',
  'Strike %': 'Percentage of pitches thrown for a strike.',
  '1st Str %': 'Percentage of plate appearances that started with a first-pitch strike.',
  'Strike%': 'Percentage of pitches thrown for a strike.',
  'Ball%': 'Percentage of pitches thrown for a ball.',
  '1stStr%': 'Percentage of plate appearances that started with a first-pitch strike.',
  BF: 'Batters faced.',
  'P/BF': 'Average pitches thrown per batter faced.',
  'Avg Velo': 'Average measured pitch velocity across pitches with a complete tracked flight.',
  'Max Velo': 'Fastest measured pitch velocity across pitches with a complete tracked flight.',
  'Tracked %': 'Percentage of recorded pitches with a complete velocity and movement measurement.',
  'Allowed LD%': 'Percentage of batted balls allowed that were line drives.',
  'Allowed Pull%': 'Percentage of batted balls allowed that were pulled by the batter.',

  // Batted-ball / contact quality
  'LD%': 'Percentage of batted balls that were line drives.',
  'GB%': 'Percentage of batted balls that were ground balls.',
  'FB%': 'Percentage of batted balls that were fly balls.',
  'Pull%': 'Percentage of batted balls hit to the batter\'s pull side.',
  'Center%': 'Percentage of batted balls hit up the middle.',
  'Oppo%': 'Percentage of batted balls hit to the opposite field.',
  'Ctr%': 'Percentage of batted balls hit up the middle.',
  LD: 'Line drives hit (or allowed).',
  GB: 'Ground balls hit (or allowed).',
  FB: 'Fly balls hit (or allowed).',
  Pull: 'Batted balls hit to the batter\'s pull side.',
  Ctr: 'Batted balls hit up the middle.',
  Oppo: 'Batted balls hit to the opposite field.',
  'Avg EV': 'Average exit velocity of batted balls.',
  'Max EV': 'Highest exit velocity recorded on a batted ball.',
  'Avg EV Allowed': 'Average exit velocity allowed on batted balls.',
  'Avg LA': 'Average launch angle of batted balls off the bat.',
  'Avg Launch': 'Average launch angle of batted balls off the bat.',
  'Avg Dist': 'Average distance traveled on batted balls.',
  'Avg/Max Dist': 'Average and max distance traveled on batted balls.',
  'Avg Distance': 'Average distance traveled on batted balls.',
  Longest: 'Longest batted ball distance recorded.',
  'Barrel%': 'Percentage of batted balls hit with the ideal combination of exit velocity and launch angle for extra-base damage.',
  'Barrel% Allowed': 'Percentage of batted balls allowed that were "barreled" — the ideal combination of exit velocity and launch angle.',
  'Hard-Hit%': 'Percentage of batted balls hit at 95+ mph exit velocity.',
  'Hard-Hit% Allowed': 'Percentage of batted balls allowed hit at 95+ mph exit velocity.',
  'Hard-Hit% (Dist)': 'Percentage of batted balls classified as hard-hit based on distance.',
  'Hard-Hit% (EV)': 'Percentage of batted balls classified as hard-hit based on exit velocity.',
  'Sweet-Spot%': 'Percentage of batted balls hit with a launch angle in the optimal 8-32° range.',
  'Park-Adj Dist': 'Average batted-ball distance adjusted for the stadium(s) it was hit in.',
  'Power Index': 'A composite score blending exit velocity and distance into a single power rating.',
  'Spray Angle': 'Average horizontal angle of batted balls, showing pull/oppo tendency.',
  'Pull EV': 'Average exit velocity on batted balls pulled by the batter.',
  'Ctr EV': 'Average exit velocity on batted balls hit up the middle.',
  'Oppo EV': 'Average exit velocity on batted balls hit the opposite way.',
  'Pull SLG': 'Slugging percentage on batted balls pulled by the batter.',
  'Oppo SLG': 'Slugging percentage on batted balls hit the opposite way.',
  'GB BABIP': 'Batting average on balls in play that were ground balls.',
  'LD BABIP': 'Batting average on balls in play that were line drives.',
  'FB BABIP': 'Batting average on balls in play that were fly balls.',
  'LD wOBA': 'wOBA generated on line drives only.',
  'FB wOBA': 'wOBA generated on fly balls only.',
  BIP: 'Balls in play: batted balls that weren\'t a strikeout, walk, or home run.',
  'BIP Allowed': 'Balls in play allowed: batted balls against this pitcher that weren\'t a strikeout, walk, or home run.',

  // Fielding
  'FLD%': 'Fielding percentage: plays made cleanly (putouts + assists) divided by total chances.',
  'Fielding %': 'Fielding percentage: plays made cleanly (putouts + assists) divided by total chances.',
  BJ: 'Buddy Jumps: assisted catches made with help from a teammate.',
  NP: 'Nice Plays: standout defensive plays beyond a routine catch.',
  'NP%': 'Nice Plays divided by total fielding chances.',
  'Nice Plays': 'Standout defensive plays beyond a routine catch.',
  'Nice Play %': 'Nice Plays divided by total fielding chances.',
  'Range Factor': 'Putouts plus assists per game, a raw measure of defensive range.',
  DER: 'Defensive Efficiency Ratio: the share of fieldable balls in play on which the team recorded an out.',
  RngR: 'Range Runs: estimated runs saved (or cost) by a fielder\'s range compared to an average fielder at that position.',
  'Range Runs': 'Estimated runs saved (or cost) by a fielder\'s range compared to an average fielder at that position.',
  'Range+': 'Range Factor scaled to league average, where 100 is average and higher is better.',
  'Rng Conf': 'Range Confidence: how reliable the range rating is, based on sample size.',
  Confidence: 'How reliable this range rating is, based on sample size.',
  'Actual Outs': 'Outs actually recorded on balls hit into this fielder\'s zone.',
  'Expected Outs': 'Outs a league-average fielder would be expected to record on the same balls in play.',
  OAA: 'Outs Above Average: actual outs minus the outs an average fielder would be expected to make on the same tracked opportunities.',
  FRV: 'Fielding Run Value: estimated runs saved above average from range, throwing, and double-play conversion.',
  'Arm Strength': 'Average velocity of a fielder\'s hardest tracked throws, using a position-specific top-throw sample. Buddy Throws are excluded, because their speed comes from a chemistry pairing rather than from one arm.',
  'Max Throw': 'Fastest tracked throw by a single fielder.',
  'Max Buddy': 'Fastest tracked Buddy Throw started by this fielder — two chemistry-linked fielders combining, where the first bounces the ball to the second, who fires it in. They run roughly twice the speed of an ordinary throw, and the partner who actually releases the ball is not identifiable from the tracking capture, so they are kept out of Arm Strength.',
  'Arm Value': 'Estimated runs saved by holding or throwing out runners compared with the league expectation for the same opportunity.',
  Holds: 'Extra-base opportunities where a runner did not attempt the additional base.',
  'Runner Outs': 'Runners thrown out while attempting an additional base.',
  'DP Opp': 'Eligible ground-ball double-play opportunities with fewer than two outs and a runner on first.',
  'DP Added': 'Double plays completed above or below the league expectation for the same opportunity context.',
  Jump: 'Average distance covered in the first three seconds after tracked contact, including reaction, burst, and route components.',
  Depth: 'Average distance from home plate at pitch release on tracked balls in play.',
  Angle: 'Average horizontal positioning angle from straightaway center field at pitch release.',
  'Back-L OAA': 'Outs Above Average on tracked opportunities requiring movement back and left.',
  'Back OAA': 'Outs Above Average on tracked opportunities requiring movement straight back.',
  'Back-R OAA': 'Outs Above Average on tracked opportunities requiring movement back and right.',
  'In-L OAA': 'Outs Above Average on tracked opportunities requiring movement in and left.',
  'In OAA': 'Outs Above Average on tracked opportunities requiring movement straight in.',
  'In-R OAA': 'Outs Above Average on tracked opportunities requiring movement in and right.',

  // Baserunning / movement tracking
  'Sprint Speed': 'Average top running speed from the fastest two-thirds of tracked competitive runs, in miles per hour.',
  Bolts: 'Tracked competitive runs reaching the league\'s elite sprint-speed threshold.',
  'Home-to-First': 'Elapsed time from contact to reaching first base.',
  '90-ft Split': 'Tracked or calibrated time to cover 90 feet.',
  'XBT Opp': 'Opportunities to take an extra base on a hit or tag-up play.',
  'XBT Holds': 'Modeled extra-base opportunities where the runner stayed at the starting base.',
  'XBT Att': 'Modeled extra-base opportunities where the runner attempted the additional base.',
  'XBT Safe': 'Attempted extra-base advances completed safely.',
  'XBT Attempt %': 'Attempts divided by modeled extra-base opportunities. This is the same rate previously labeled XBT%.',
  'XBT Safe/Att': 'Safe advances divided by attempted extra-base advances; unavailable with no attempts.',
  'XBT Safe/Opp': 'Safe advances divided by modeled extra-base opportunities; unavailable with no opportunities.',
  '1st→3rd 1B': 'First to third on a single. Cell shows opportunities / holds / attempts / safe advances / outs.',
  '2nd→H 1B': 'Second to home on a single. Cell shows opportunities / holds / attempts / safe advances / outs.',
  '1st→H 2B': 'First to home on a double. Cell shows opportunities / holds / attempts / safe advances / outs.',
  'Tag 1st→2nd': 'Tag-up from first to second. Cell shows opportunities / holds / attempts / safe advances / outs.',
  'Tag 2nd→3rd': 'Tag-up from second to third. Cell shows opportunities / holds / attempts / safe advances / outs.',
  'Tag 3rd→H': 'Tag-up from third to home. Cell shows opportunities / holds / attempts / safe advances / outs.',
  'Modeled Opp': 'Extra-base opportunities with a modeled run value. Compare with XBT Opp for model coverage.',
  'Modeled %': 'Share of recorded extra-base opportunities with a modeled run value; unavailable without an opportunity.',
  'Exp. Rbaser': 'Experimental extra-base run value on modeled opportunities. WAR BsR can differ because it also includes double-play avoidance.',
  'Speed Runs': 'Competitive runner or batter runs qualifying for the sprint-speed sample.',
  'Max Speed': 'Highest sprint speed among qualifying competitive runs, in miles per hour.',
  'H→1 Samples': 'Tracked runs with a measured home-to-first time.',
  '90-ft Samples': 'Tracked runs with a measured 90-foot split.',
  Throws: 'Tracked throws with a measured peak speed. Buddy Throws are listed separately.',
  'Buddy Throws': 'Tracked Buddy Throws with measured speed; excluded from individual Arm Strength.',
  'Arm Opp': 'Tracked extra-base opportunities assigned to this fielder for arm evaluation.',
  'Adv Allowed': 'Runners who advanced safely on tracked arm opportunities.',
  'OAA Opp': 'Tracked primary fielding opportunities with a modeled catch probability and OAA.',
  'DP Runs': 'Modeled run value of eligible double-play opportunities.',
  'Jump Samples': 'Tracked fielder movements with a measured three-second Jump.',
  Reaction: 'Distance gained or lost during the reaction phase of tracked Jump, in feet.',
  Burst: 'Distance covered during the burst phase of tracked Jump, in feet.',
  'Route Eff.': 'Average measured route efficiency on tracked Jump samples.',
  'Position Samples': 'Tracked fielding opportunities with a measured pre-pitch position.',
  'XBT%': 'Percentage of extra-base opportunities in which the runner attempted the additional base.',
  'XBT Safe%': 'Percentage of attempted extra-base advances completed safely.',
  'XBT Outs': 'Outs made while attempting an additional base.',

  // WAR-family (career page)
  Rbat: 'Batting Runs: runs contributed above average through hitting.',
  Rbaser: 'Baserunning Runs: runs contributed above average through baserunning.',
  Rfield: 'Fielding Runs: runs contributed above average through defense.',
  Rpos: 'Positional adjustment: run value adjustment for the defensive difficulty of the position played.',
  RAA: 'Runs Above Average: total runs contributed above a league-average player.',
  WAA: 'Wins Above Average: RAA converted into a wins total.',
  RAR: 'Runs Above Replacement: total runs contributed above a bench-level replacement player.',
  WAR: 'Wins Above Replacement: RAR converted into a wins total — the standard all-in-one value stat.',

  // Star pitch / usage
  'Contact %': 'Percentage of Star Hit uses that resulted in contact.',
  'RBI/Use': 'Average RBI driven in per Star Hit use.',
  'RISP AVG': 'Batting average with runners in scoring position (2nd or 3rd base).',
  'Opp RISP AVG': 'Opponent batting average allowed with runners in scoring position.',

  // Park factors
  'Hard-Hit': 'How much this park inflates or deflates hard-hit ball rate vs. a neutral park (1.00 = neutral).',
  Barrel: 'How much this park inflates or deflates barrel rate vs. a neutral park (1.00 = neutral).',

  // Ratings
  OVR: 'Overall rating.',
  BAT: 'Batting rating.',
  PIT: 'Pitching rating.',
  FLD: 'Fielding rating.',
  SPD: 'Speed rating.',
}

// Normalizes trivial formatting differences (case, whitespace) so a label like "obp" or " OBP "
// still resolves, without silently matching unrelated short strings.
export function getStatDescription(label) {
  if (!label || typeof label !== 'string') return null
  const trimmed = label.trim()
  if (STAT_DESCRIPTIONS[trimmed]) return STAT_DESCRIPTIONS[trimmed]
  const upper = trimmed.toUpperCase()
  const match = Object.keys(STAT_DESCRIPTIONS).find((key) => key.toUpperCase() === upper)
  return match ? STAT_DESCRIPTIONS[match] : null
}
