// What the tracker believes happened, in plain English, derived only from
// structured facts.
//
// WHAT THIS IS FOR. During a live game there is no way to check the tracker
// except by reading numbers off a page and comparing them, in your head,
// against a play you half remember. That does not scale past an inning. A
// sentence does: "Peach hit a ground ball toward shortstop. Waluigi attempted
// to field the ball but did not make contact. Peach reached first" is either
// what happened or obviously not, and the operator knows which within a second
// of the play ending.
//
// WHAT THIS IS NOT. It is not commentary, and there is no language model
// anywhere near it. Every sentence is generated by a rule from a named field,
// and every sentence carries the field it came from. If the tracker is wrong,
// the sentence is wrong in exactly the way the data is wrong, which is the
// entire point -- a narrative that smoothed over missing data would hide the
// bug it exists to expose.
//
// THE RULES THAT KEEP IT HONEST
//
//   1. Separate facts stay separate sentences. A fielding ATTEMPT, physical
//      CONTACT with the ball, and POSSESSION of it are three different
//      observations with three different sources, and a play can have any
//      combination of them. Collapsing them into "made the play" or "missed
//      it" is what makes a tracker bug invisible.
//
//   2. Nothing is asserted more confidently than its source. A fact the game
//      declared is `observed`. A fact computed from measurements is `derived`.
//      A fact that follows from the rules of baseball rather than from a
//      measurement is `inferred`. A signal that fired without a resolvable
//      meaning is `unknown`, and it says so in the sentence.
//
//   3. A capability is never an activation. See tracker_abilities.mjs.
//
//   4. A physical boot is never an official error. The game charges errors;
//      the memory reader sees a ball not held. Those are different claims and
//      only one of them is in the data.

import {
  isFairPlay,
} from './tracker_play_join.mjs'
import {
  trackerBootLeftTheHitStanding,
} from './tracker_play_events.mjs'
import {
  resolveCarryAbility,
  resolveFieldingAbility,
  resolveStarAbility,
  resolveThrowingAbility,
} from './tracker_abilities.mjs'

export const CLAUSE_STATUSES = Object.freeze([
  'observed', 'derived', 'inferred', 'unknown', 'pending', 'not_applicable', 'mismatch',
])

export const NARRATIVE_STATUSES = Object.freeze([
  'complete', 'partial', 'pending', 'unavailable',
])

const POSITION_PHRASES = {
  P: 'the pitcher', C: 'the catcher', '1B': 'the first baseman',
  '2B': 'the second baseman', '3B': 'the third baseman', SS: 'the shortstop',
  LF: 'the left fielder', CF: 'the center fielder', RF: 'the right fielder',
}

const BASE_PHRASES = {
  first: 'first', second: 'second', third: 'third', home: 'home',
}

const TRAJECTORY_NOUNS = {
  G: 'ground ball', L: 'line drive', F: 'fly ball', B: 'bunt',
}

const RESULT_PHRASES = {
  '1B': 'a single', '2B': 'a double', '3B': 'a triple',
  HR: 'a home run', IPHR: 'an inside-the-park home run',
  BB: 'a walk', HBP: 'a hit by pitch', K: 'a strikeout',
  GO: 'a groundout', FO: 'a flyout', LO: 'a lineout',
  DP: 'a double play', TP: 'a triple play', SF: 'a sacrifice fly',
  SH: 'a sacrifice bunt', FC: "a fielder's choice", ROE: 'a reached-on-error',
}

// Results in which the batter-runner was retired on the batted ball. The
// complement of the safe set an error can be charged on (1B/2B/3B/ROE/FC in
// tracker_play_events.mjs); a bobble on one of these cost the defence nothing
// the rules recognise. SF and SH are absent on purpose: the batter is out, but
// a runner advanced, and whether the fumble is what let them is a judgement.
const RETIRED_BATTER_RESULTS = new Set(['GO', 'FO', 'LO', 'DP', 'TP'])

// Direction bands, in degrees off dead centre, positive toward the first-base
// side. The infield and outfield get different vocabularies because "toward
// shortstop" and "toward left-center" describe the same direction at different
// depths, and a ground ball that is called a fly ball's destination reads as a
// tracker error to anyone checking it.
const OUTFIELD_ZONES = [
  [-90, -37.5, 'the left-field line'],
  [-37.5, -26, 'left field'],
  [-26, -14, 'left-center'],
  [-14, 14, 'center field'],
  [14, 26, 'right-center'],
  [26, 37.5, 'right field'],
  [37.5, 90, 'the right-field line'],
]

const INFIELD_ZONES = [
  [-90, -30, 'third base'],
  [-30, -9, 'shortstop'],
  [-9, 9, 'the pitcher'],
  [9, 30, 'second base'],
  [30, 90, 'first base'],
]

// How far out a ball has to finish before the outfield vocabulary describes it.
// "Toward the left-field line" for a ball that stopped sixteen feet in front of
// the plate is not a rounding error, it is a different play.
const INFIELD_ZONE_MAX_FEET = 120

function zoneFor(angleDeg, trajectory, distanceFeet = null) {
  if (!Number.isFinite(angleDeg)) return null
  // The trajectory letter decides it when there is one. When there is not --
  // an unclassified ball, or a foul, which the tracker never classifies -- the
  // measured distance decides instead of defaulting to the outfield, which is
  // how a bunt ended up described as a ball down the left-field line.
  const infield = (trajectory === 'G' || trajectory === 'B')
    || (!trajectory && Number.isFinite(distanceFeet) && distanceFeet < INFIELD_ZONE_MAX_FEET)
  const bands = infield ? INFIELD_ZONES : OUTFIELD_ZONES
  for (const [low, high, label] of bands) {
    if (angleDeg >= low && angleDeg < high) return label
  }
  return null
}

/**
 * Direction of a point in the ball's coordinate frame, in degrees off centre.
 *
 * The frame is the one parkGeometry.js documents: -Z toward centre field, +X
 * toward first base. So a positive angle is toward right field.
 */
export function directionDegrees(point) {
  if (!Array.isArray(point) || point.length < 3) return null
  const [x, , z] = point
  if (!Number.isFinite(x) || !Number.isFinite(z)) return null
  return (Math.atan2(x, -z) * 180) / Math.PI
}

// A foul goes outside the lines, where the fair-ball zone tables have no
// vocabulary: every one of them lands in the outermost band and comes back
// "the left-field line". The tracker's own log describes a foul by which side
// of the plate it went to, and so does this.
function foulSide(angleDeg) {
  if (!Number.isFinite(angleDeg)) return null
  if (angleDeg <= -45) return 'the third-base side'
  if (angleDeg >= 45) return 'the first-base side'
  return 'straight back'
}

function isFoulPlay(play) {
  if (!play) return false
  return play.batted_ball_class === 'foul' || play.batted_ball_class === 'foul_home_run'
}

// One definition of the scale, the same one tracker_preview_state.mjs uses.
const FEET_PER_UNIT = 3.280839895

// How far the ball actually finished from the plate. The at-bat's own distance
// is the right answer when the join is sound, but a play carries its own
// measurement and that is the one that has to decide the vocabulary used to
// describe THAT play.
function measuredDistanceFeet(atBat, play) {
  const units = Number(play?.landing?.distance_units)
  if (Number.isFinite(units)) return units * FEET_PER_UNIT
  const stated = Number(atBat?.hit_distance_ft)
  return Number.isFinite(stated) ? stated : null
}

function positionPhrase(position) {
  return POSITION_PHRASES[position] || (position ? `the ${position}` : 'a fielder')
}

// Sentence-initial. "the center fielder recovered the ball" reads as a
// truncated sentence, which in a QA console reads as a rendering bug.
function capitalized(phrase) {
  const text = String(phrase ?? '')
  return text ? text[0].toUpperCase() + text.slice(1) : text
}

// The character's name when the capture resolved one, and the position when it
// did not. Never a bare position code, which reads as a typo in a sentence.
// An id the 60 Hz capture could not name. Miis are not in the game's character
// table, so every one of them arrives as `char 78` and used to be narrated as
// "the first baseman" -- a sentence about a position where every other fielder
// gets a name.
const UNNAMED_CHARACTER = /^char \d+$/

// How the derivation's `impulse` reads in a sentence. Every phrase names the
// thing that arrived, because that is what was measured -- an object reaching
// the fielder on the exact frame the impulse began. `knockdown` stays vague on
// purpose: the flag marks the impact and never says what caused it, and the
// park-specific hazard clauses are the ones entitled to name that.
const KNOCKBACK_IMPULSE_PHRASE = {
  batted_ball: 'that was the force of the batted ball, taken on the frame it reached them',
  thrown_ball: 'that was the force of the throw, taken on the frame it arrived',
  knockdown: 'something floored them on that frame, and the flag does not say what',
}

// `leap` is the one impulse that is not something arriving, so it gets its own
// sentence rather than a clause hung off "was driven back". A fielder who
// catches in mid-air keeps travelling, and that follow-through passes every
// knockback test; the airborne flag on the possession frame is what says the
// jump, not the ball, is what moved them.
const LEAP_CARRY_EVIDENCE =
  'airborne on the frame they took the ball, so the drift is the jump they were already in'

// A knockback under a unit is the recoil of taking the ball, not an event, and
// the rest of the narrative already uses a one-unit floor for ball-holding
// moves.
const KNOCKBACK_NARRATIVE_FLOOR_UNITS = 1.0

/**
 * The name to print for a fielder the capture identified only by id.
 *
 * The tracker log publishes the defending side's whole alignment
 * ([TRACKER_LINEUP] fielding=P=...,C=...), and it names the Mii the way the
 * game does -- "Orange Mii (M)". So the name exists in this at-bat already;
 * it is simply on the other feed. Falling back to it beats printing a position
 * where a name belongs, and it costs nothing when the capture knew the name.
 */
function namedFielder(character, position, atBat = null) {
  if (character && !UNNAMED_CHARACTER.test(character)) return character
  const announced = position ? atBat?.fielding_alignment?.[position] : null
  return announced || null
}

function fielderPhrase(character, position, atBat = null) {
  const name = namedFielder(character, position, atBat)
  if (name) return position ? `${name} (${position})` : name
  return positionPhrase(position)
}

function actorPhrase(event, atBat = null) {
  return fielderPhrase(
    event?.character,
    event?.by || event?.thrower_position || null,
    atBat,
  )
}

class NarrativeBuilder {
  constructor() {
    this.clauses = []
    this.timeline = []
    this.counter = 0
  }

  add({ category, text, status, source, evidence = {}, t = null, frame = null }) {
    this.counter += 1
    const id = `c${String(this.counter).padStart(2, '0')}-${category}`
    this.clauses.push({
      id, category, text, status, source,
      evidence: { ...evidence, ...(t != null ? { t } : {}), ...(frame != null ? { frame } : {}) },
    })
    if (t != null || frame != null) {
      this.timeline.push({ id, category, t, frame, text })
    }
    return id
  }
}

// --- 1. contact, trajectory and location ------------------------------------

function describeContact(builder, { atBat, play }) {
  const batter = atBat.batter_name || 'The batter'
  const result = atBat.result

  if (result === 'K') {
    const type = atBat.strikeout_type
    const how = type === 'KS' ? ' swinging' : type === 'KL' ? ' looking' : ''
    builder.add({
      category: 'contact',
      text: `${batter} struck out${how}.`,
      status: type ? 'observed' : 'derived',
      source: type ? 'plate_appearance.strikeout_type' : 'plate_appearance.result',
      evidence: { result, strikeout_type: type ?? null },
    })
    return
  }
  if (result === 'BB' || result === 'HBP') {
    builder.add({
      category: 'contact',
      text: result === 'BB'
        ? `${batter} walked.`
        : `${batter} was hit by a pitch.`,
      status: 'observed',
      source: 'plate_appearance.result',
      evidence: { result },
    })
    return
  }

  const point = play?.landing?.at || play?.first_touch?.at || null
  const measuredAngle = directionDegrees(point)

  // A FOUL BALL IS NOT THIS AT-BAT'S BATTED BALL. When nothing fair joined,
  // outcomePlayFor lets a foul stand in so the page still shows the fielding it
  // does have -- but narrating it through the batted-ball path describes a ball
  // that went out of play as if it were the ball the at-bat was decided on. The
  // tracker never classifies a foul's trajectory, so that path also had no
  // letter to work with and produced "hit a ball the tracker did not classify",
  // pointed at an outfield zone, for balls that went foul near the plate.
  if (isFoulPlay(play)) {
    const side = foulSide(measuredAngle)
    const back = play.batted_ball_class === 'foul_home_run'
    builder.add({
      category: 'contact',
      text: `${batter} fouled one off${side ? ` toward ${side}` : ''}${back ? ', out of the park' : ''}.`
        + ' The tracker has no fair batted ball joined to this plate appearance,'
        + ' so what follows is the fielding on the foul, not on the ball that ended it.',
      status: 'observed',
      source: 'player_tracking_play.batted_ball_class + landing.at (ball-frame direction)',
      evidence: {
        batted_ball_class: play.batted_ball_class,
        fair_or_foul: play.fair_or_foul ?? null,
        direction_deg: Number.isFinite(measuredAngle)
          ? Math.round(measuredAngle * 10) / 10 : null,
        result,
      },
      t: 0,
      frame: play.contact_timer ?? null,
    })
    return
  }

  // The capture measures how the batter offered at the pitch; the tracker log
  // only measures how hard the ball left, which cannot tell a bunt from a
  // mishit. Where the two feeds disagree the measurement wins.
  const trajectory = (play?.contact_type === 'bunt' ? 'B' : atBat.trajectory) || null
  // An unclassified batted ball says so. "a batted ball" reads like a
  // deliberate description and hides the fact that the tracker never called
  // this one a grounder, a liner or a fly.
  const noun = TRAJECTORY_NOUNS[trajectory] || 'ball the tracker did not classify'
  const angle = Number.isFinite(measuredAngle)
    ? measuredAngle
    : (Number.isFinite(Number(atBat.hit_angle_deg)) ? Number(atBat.hit_angle_deg) : null)
  const zone = zoneFor(angle, trajectory, measuredDistanceFeet(atBat, play))

  // "deep" is a measurement, not a flourish: it is said only when a measured
  // distance says so, and the distance travels with the clause.
  const distance = Number(atBat.hit_distance_ft)
  const deep = Number.isFinite(distance) && distance >= 300 && trajectory !== 'G'
  const nounPhrase = deep && trajectory ? `a deep ${noun}` : `a ${noun}`

  if (!trajectory && !zone) {
    builder.add({
      category: 'contact',
      text: `${batter} put the ball in play. The tracker did not resolve its trajectory or direction.`,
      status: 'unknown',
      source: 'plate_appearance.trajectory + player_tracking_play.landing',
      evidence: { trajectory: null, angle_deg: null, result },
      t: play ? 0 : null,
      frame: play?.contact_timer ?? null,
    })
    return
  }

  const where = zone ? ` toward ${zone}` : ''
  builder.add({
    category: 'contact',
    text: `${batter} hit ${nounPhrase}${where}.`,
    status: Number.isFinite(measuredAngle) ? 'derived' : (zone ? 'derived' : 'observed'),
    source: Number.isFinite(measuredAngle)
      ? 'player_tracking_play.landing.at (ball-frame direction)'
      : 'plate_appearance.trajectory + plate_appearance.hit_angle_deg',
    evidence: {
      trajectory,
      trajectory_source: trajectory ? 'tracker_batted_ball' : null,
      direction_deg: angle == null ? null : Math.round(angle * 10) / 10,
      direction_source: Number.isFinite(measuredAngle)
        ? 'measured_endpoint_coordinates' : 'tracker_spray_angle',
      zone,
      hit_distance_ft: Number.isFinite(distance) ? distance : null,
      deep_threshold_ft: deep ? 300 : null,
      exit_velocity_mph: atBat.exit_velocity_mph ?? null,
      launch_angle_deg: atBat.launch_angle_deg ?? null,
    },
    t: play ? 0 : null,
    frame: play?.contact_timer ?? null,
  })

}

function describeBatterStarSwing(builder, { atBat }) {
  const batter = atBat.batter_name || 'The batter'
  const star = resolveStarAbility({
    characterName: batter, used: Boolean(atBat.star_hit_used), kind: 'swing',
  })
  if (!atBat.star_hit_used) return

  const ability = star.status === 'confirmed'
    ? star.abilityName
    : star.status === 'standard' ? 'the standard star swing' : 'a star swing'
  const pitches = atBat.pitches || []
  const hasPerPitchFlags = pitches.some((pitch) => Object.hasOwn(pitch, 'is_star_swing'))
  const starPitches = pitches.filter((pitch) => pitch.is_star_swing)
  let context = ''
  if (hasPerPitchFlags && starPitches.length) {
    const decisive = pitches.at(-1)
    if (decisive?.is_star_swing && decisive.result === 'in_play') {
      context = ' on the ball put in play'
    } else if (atBat.result === 'K' && decisive?.is_star_swing) {
      context = ' on strike three and missed'
    } else {
      const attempts = starPitches.map((pitch) => {
        const number = pitch.pitch_number_pa ?? pitches.indexOf(pitch) + 1
        const outcome = pitch.result === 'swinging_miss' ? 'missed'
          : pitch.result === 'foul' ? 'fouled off'
            : pitch.result === 'in_play' ? 'put in play' : pitch.result
        return `pitch ${number}${outcome ? ` (${outcome})` : ''}`
      }).join(', ')
      context = ` on ${attempts}; the deciding pitch was not a star swing`
    }
  }

  if (star.status === 'confirmed') {
    builder.add({
      category: 'ability',
      text: `${batter} used ${ability}${context}.`,
      status: 'observed',
      source: 'tracker log "used a star swing!" + CHARACTER_STAR_SWING',
      evidence: {
        ...star,
        star_hit_used: true,
        star_hit_connected: atBat.star_hit_connected ?? null,
        star_pitch_numbers: starPitches.map((pitch) => pitch.pitch_number_pa),
      },
    })
  } else if (star.status === 'standard') {
    builder.add({
      category: 'ability',
      text: `${batter} used ${ability}${context}, which every non-captain shares.`,
      status: 'observed',
      source: 'tracker log "used a star swing!" + CHARACTER_STAR_SWING',
      evidence: {
        ...star,
        star_hit_used: true,
        star_hit_connected: atBat.star_hit_connected ?? null,
        star_pitch_numbers: starPitches.map((pitch) => pitch.pitch_number_pa),
      },
    })
  } else if (star.status === 'unresolved') {
    builder.add({
      category: 'ability',
      text: `${batter} used ${ability}${context}. The roster does not name which swing that is.`,
      status: 'unknown',
      source: 'tracker log "used a star swing!"',
      evidence: {
        ...star,
        star_hit_used: true,
        star_hit_connected: atBat.star_hit_connected ?? null,
        star_pitch_numbers: starPitches.map((pitch) => pitch.pitch_number_pa),
      },
    })
  }
}

// --- 2-4. fielding attempt, contact, possession -----------------------------

// The fielder the game itself names as this handoff's Buddy partner, or null.
//
// A Buddy Throw carries `buddy_thrower_position` and `buddy_partner_position`
// straight from the game's own state. Action code 7 with no such throw anywhere
// on the play is a redirection the tracker cannot attribute to chemistry.
function buddyPartnerFor(play, event) {
  for (const throwRecord of play?.throws || []) {
    if (!throwRecord.buddy_throw) continue
    const pair = [throwRecord.buddy_thrower_position, throwRecord.buddy_partner_position]
    if (!pair.includes(event.by)) continue
    return pair.find((position) => position && position !== event.by) ?? null
  }
  return null
}

// A fielder knocking the ball out of the park, as opposed to a ball that
// carried out on its own. Every clause is a measurement: the game called it a
// home run, this fielder touched it with the ball ABOVE THE GROUND (a ground
// ball a fielder boots is not this), and no one ever took possession -- which
// is what rules out a ball that was deflected and then retrieved.
const DEFLECTED_OUT_MIN_HEIGHT_UNITS = 0.5

function deflectedOutOfThePark(play, event) {
  if (!play || !event) return false
  if (!(play.home_run === true || play.batted_ball_class === 'home_run')) return false
  if (event.secured === true || event.ball_contact !== 'confirmed') return false
  if (play.first_touch) return false
  const height = Number(event.ball_at?.[1])
  return Number.isFinite(height) && height > DEFLECTED_OUT_MIN_HEIGHT_UNITS
}

function describeFieldingEvent(builder, event, { play, atBat = null }) {
  const who = actorPhrase(event, atBat)
  const ability = resolveFieldingAbility({
    characterName: event.character,
    actionCode: event.action_code,
    catchType: event.catch_type ?? null,
    observedDive: event.dive === true,
    observedLeap: event.leap === true,
  })
  const base = {
    source: 'player_tracking_play.fielding_events[]',
    evidence: {
      by: event.by,
      character: event.character ?? null,
      character_id: event.character_id ?? null,
      action_code: event.action_code ?? null,
      mechanic: event.mechanic,
      fielding_attempt: event.fielding_attempt,
      ball_contact: event.ball_contact,
      secured: event.secured,
      official_error: event.official_error,
      confidence: event.confidence,
      contact_source: event.contact_source,
      distance_units: event.distance_units ?? null,
      closest_distance_units: event.closest_distance_units ?? null,
      // Three-dimensional, so it is the only one of the three that knows how
      // far above the fielder the ball was.
      closest_reach_units: event.closest_reach_units ?? null,
      within_reach: event.within_reach ?? null,
      last_contact_fielder: event.last_contact_fielder ?? null,
      fielding_contact_counter: event.fielding_contact_counter ?? null,
      // The airborne flag accompanies a LEAP and never a dive, so it stays
      // attempt context rather than a reach classifier.
      airborne_near_contact: event.airborne_near_contact ?? null,
      // How the fielder got to the ball, from the actor's own `catch_type`
      // byte. The roster resolver decides whether that observed input is an
      // ordinary dive or this character's named dive/reach ability.
      catch_type: event.catch_type ?? null,
      approach: event.approach ?? null,
      dive: event.dive === true,
      leap: event.leap === true,
      ball_landed_before_contact: event.ball_landed_before_contact ?? null,
      trajectory_turn_degrees: event.trajectory_turn_degrees ?? null,
      incoming_speed_ups: event.incoming_speed_ups ?? null,
      outgoing_speed_ups: event.outgoing_speed_ups ?? null,
    },
    t: event.t ?? null,
    frame: event.frame ?? null,
  }

  const Who = capitalized(who)
  // Rule 1: the approach to the ball is its own observation. Whether the
  // fielder dove is a different claim from whether he then held on to it.
  if (event.dive === true || event.leap === true || ability.status === 'confirmed') {
    const move = event.dive === true ? 'dove' : event.leap === true ? 'leapt' : 'went'
    builder.add({
      ...base,
      category: 'approach',
      // There is one dive/jump input, so a character mapped to Super Dive who
      // dives has used Super Dive. Saying only "dove" here understated what
      // the capture actually saw.
      text: ability.status === 'confirmed'
        ? `${Who} used ${ability.abilityName} to reach the ball.`
        : `${Who} ${move} for the ball.`,
      status: 'observed',
      source: 'player_tracking_play.fielding_events[].catch_type',
      evidence: { ...base.evidence, ability_resolution: ability },
    })
  }
  if (event.event_type === 'possession') {
    const caught = play?.caught_in_flight
    const height = Number(event.ball_height_units)
    const offGround = Number.isFinite(height) && height > 2.5
    // Taking a teammate's buddy toss is catching a throw. Describing it as
    // securing the ball "after it landed" put two fielders on one batted ball
    // and read as the tracker seeing the play twice.
    const tossedBy = event.mechanic === 'buddy_receive' ? event.received_from : null
    const tail = tossedBy
      ? ` on the buddy toss from ${positionPhrase(tossedBy)}`
      : caught
        ? ' before it landed'
        : (play?.landing ? ' after it landed' : '')
    builder.add({
      ...base,
      category: 'possession',
      text: `${Who} ${tossedBy ? 'took the ball' : 'secured the ball'}${tail}`
        + `${offGround ? `, ${height.toFixed(1)} units off the ground` : ''}.`,
      status: 'observed',
      evidence: {
        ...base.evidence,
        caught_in_flight: caught ?? null,
        ball_height_units: Number.isFinite(height) ? height : null,
        landed_first: play?.landing ? true : false,
        received_from: tossedBy,
      },
    })
    return
  }

  // A fielding action that is not possession. Attempt, contact and outcome are
  // three separate claims and the sentence keeps them apart.
  if (event.mechanic === 'egg') {
    builder.add({
      ...base,
      category: 'mechanic',
      text: event.ball_contact === 'confirmed'
        ? `A Yoshi Egg forced ${who} to misplay the first contact.`
        : `A Yoshi Egg action fired at ${who}, and the tracker could not confirm contact.`,
      status: event.ball_contact === 'confirmed' ? 'observed' : 'unknown',
    })
    return
  }
  if (event.mechanic === 'buddy') {
    // Action code 7 does not establish a chemistry Buddy Throw, but it DOES
    // establish an intentional dive-and-toss. The fixed outgoing speed and new
    // heading show control rather than a random deflection, so this is a secure
    // followed immediately by a pass whether or not chemistry state is present.
    //
    // What the code itself is worth saying: the ball leaves at a fixed speed
    // (23.28 u/s in every occurrence measured, whatever it came in at) on a
    // new heading, so it is a deliberate redirection rather than a deflection.
    const partner = buddyPartnerFor(play, event)
    builder.add({
      ...base,
      category: 'mechanic',
      text: partner
        ? `${Who} secured and redirected the ball to ${positionPhrase(partner)} with a buddy toss during the Buddy sequence.`
        : `${Who} secured and redirected the ball to another fielder with a buddy toss.`,
      status: event.ball_contact === 'confirmed' ? 'observed' : 'unknown',
      evidence: {
        ...base.evidence,
        buddy_partner_position: partner,
        why: partner
          ? 'a Buddy Throw on this play names the chemistry partner; action 7 itself establishes the secure-and-toss'
          : 'action 7 establishes the secure-and-toss, but no Buddy state claims a chemistry pairing',
      },
    })
    return
  }
  // Mario's Fire Swing turns the ball into a fireball, and the first fielder
  // to reach it cannot hold it. Same shape as Yoshi's egg, same consequence:
  // the batter's ability made the misplay, so it is not the fielder's.
  if (event.mechanic === 'star_ball') {
    const batter = play?.batter
    const ball = batter === 'Mario' ? "Mario's fireball" : "the batter's star-swing ball"
    builder.add({
      ...base,
      category: 'mechanic',
      text: event.ball_contact === 'confirmed'
        ? `${capitalized(ball)} forced ${who} to lose the first contact.`
        : `${capitalized(ball)} action fired at ${who}, and the tracker could not confirm contact.`,
      status: event.ball_contact === 'confirmed' ? 'observed' : 'unknown',
      evidence: {
        ...base.evidence,
        batter: batter ?? null,
        action_code: event.action_code,
        why: 'action code 4 has only ever been recorded with Mario batting, and the operator names it as the Fire Swing fireball',
      },
    })
    return
  }
  if (event.mechanic === 'special_unknown') {
    builder.add({
      ...base,
      category: 'mechanic',
      text: `${Who} used an unresolved special fielding action`
        + (event.ball_contact === 'confirmed' ? ' and contacted the ball.'
          : event.ball_contact === 'missed' ? ' without contacting the ball.'
            : '; the tracker could not determine whether contact occurred.'),
      status: 'unknown',
      evidence: {
        ...base.evidence,
        ability_resolution: ability,
        unresolved_action_code: event.action_code,
      },
    })
    return
  }

  // Ordinary attempt: 2 or 3.
  if (event.ball_contact === 'confirmed') {
    builder.add({
      ...base,
      category: 'ball_contact',
      text: `${Who} contacted the ball but failed to secure it.`,
      status: 'observed',
      evidence: { ...base.evidence, ability_resolution: ability },
    })
    // THE BALL WENT OUT OFF THE FIELDER. A home run whose only contact was a
    // confirmed touch above the ground that nobody then took possession of is
    // a ball a fielder knocked over the wall -- which is the whole story of
    // the play and the reason the batter is circling. Daisy Cruiser 2026-09-04
    // PA 57 is the case: Yoshi got a glove on Red Kritter's line drive 79.8
    // units out and 1.1 units up, bounced it out of the park, and the console
    // said only that he "failed to secure it" and then, five sentences later,
    // that the plate appearance was a home run, with nothing joining the two.
    if (deflectedOutOfThePark(play, event)) {
      builder.add({
        category: 'outcome',
        text: `The ball left the park off ${who}; no fielder took possession of it, `
          + `so ${event.character || 'the fielder'} put it over the wall rather than the ball carrying out.`,
        status: 'derived',
        source: 'player_tracking_play.home_run with a confirmed elevated contact and no possession',
        evidence: {
          batted_ball_class: play?.batted_ball_class ?? null,
          home_run: play?.home_run ?? null,
          contact_height_units: event.ball_at?.[1] ?? null,
          contact_distance_units: play?.landing?.distance_units ?? null,
          first_touch: play?.first_touch ?? null,
          why: 'the ball was struck above the ground by a fielder and never came into anyone’s hands',
        },
        t: event.t ?? null,
        frame: event.frame ?? null,
      })
      // A ball that left the park has no error to determine, so stop before
      // the fallback sentence below says one is unavailable.
      return
    }
    // The physical boot and the scoring decision are different claims.
    //
    // On a play the batter did not survive, the second one is not open: an
    // error requires a misplay that prolonged the time at bat, prolonged the
    // life of a runner, or let a runner advance (OBR 9.12(a)(1)), and a fumble
    // the fielder recovered from in time to retire the batter did none of the
    // three. Saying "no determination is available" there states a scorer's
    // ruling as unknown when the rulebook settles it -- and it is the exact
    // question an operator asks when a bobbled ball still got the out.
    if (RETIRED_BATTER_RESULTS.has(atBat?.result)) {
      // The third limb of the rule -- "permits a runner to advance" -- is the
      // only one still open, and only when a runner actually moved. Saying so
      // is the difference between a ruling and a claim.
      const advanced = (atBat.runner_assignments || []).filter((assignment) => !assignment.isBatter
        && assignment.destination && assignment.destination !== 'out'
        && assignment.destination !== assignment.origin)
      builder.add({
        category: 'scoring',
        text: `No error is charged for that failure to secure: ${atBat.batter_name || 'the batter'} `
          + 'was still retired on the play, so it prolonged neither the time at bat nor the life of '
          + 'the batter-runner, and failing to complete a double play is not itself an error.'
          + (advanced.length
            ? ` Whether it let ${advanced.map((assignment) => assignment.runner?.characterName || 'a runner').join(' and ')}`
              + ' advance is the scorer\'s call, and the capture cannot settle it.'
            : ''),
        status: 'derived',
        source: 'OBR 9.12(a)(1) applied to plate_appearance.result',
        evidence: {
          official_error: event.official_error,
          result: atBat.result,
          rule: 'OBR 9.12(a)(1)',
          runners_advanced: advanced.map((assignment) => ({
            runner: assignment.runner?.characterName ?? null,
            origin: assignment.origin,
            destination: assignment.destination,
          })),
          why: 'an error is a misplay that prolongs the at-bat, prolongs a runner’s life, or permits an advance',
        },
      })
      return
    }
    // The at-bat may already carry the charge for this very boot. Saying "no
    // determination is available" and then "an error is charged to X" two
    // sentences later is the console contradicting itself about the same
    // event, which is exactly what the operator reads the narrative to catch.
    if (atBat?.is_error && atBat.error_kind === 'fielding'
        && atBat.error_character === event.character) {
      // AN ERROR THAT DID NOT PUT THE BATTER ON. When the ball reached the
      // ground untouched and an outfielder booted it, the batter already had
      // his base -- the hit stands and the charge is for the bases that
      // followed. Saying "the batter reached because of it" alongside a
      // recorded double is the console contradicting the result it just
      // printed.
      const keptTheHit = trackerBootLeftTheHitStanding(event)
      builder.add({
        category: 'scoring',
        text: `That failure to secure is the error charged to ${event.character}`
          + `${atBat.error_position ? ` at position ${atBat.error_position}` : ''}: the ball was `
          + 'reached with ordinary effort and not held, and '
          + (keptTheHit
            ? 'runners advanced because of it. The ball had already reached the ground '
              + 'untouched in the outfield, so the batter earned his base and keeps the hit.'
            : 'the batter reached because of it.'),
        status: 'derived',
        source: 'plate_appearance.is_error applied to the fielding event that caused it',
        evidence: {
          error_character: atBat.error_character,
          error_position: atBat.error_position ?? null,
          mechanic: event.mechanic,
          dive: event.dive ?? null,
          leap: event.leap ?? null,
          within_reach: event.within_reach ?? null,
          closest_distance_units: event.closest_distance_units ?? null,
          ball_landed_before_contact: event.ball_landed_before_contact ?? null,
          kept_the_hit: keptTheHit,
          rule: 'OBR 9.12(a)(1)',
          why: keptTheHit
            ? 'ordinary effort, confirmed contact, not secured, and the batter was already safe '
              + 'when the ball was booted -- the error is charged for the advance'
            : 'ordinary effort, confirmed contact, not secured, and the batter was safe',
        },
      })
      return
    }
    builder.add({
      category: 'scoring',
      text: 'No official error determination is available for that failure to secure.',
      status: 'not_applicable',
      source: 'player_tracking_play.fielding_events[].official_error',
      evidence: {
        official_error: event.official_error,
        why: 'the capture observes possession, not the scorer’s ruling',
      },
    })
    return
  }
  // A one-frame animation while the ball is 35 units overhead is not a play on
  // the ball, and calling it an attempt is what let a home run read as a
  // fielder who might have had it.
  if (event.within_reach === false) {
    const reach = Number(event.closest_reach_units)
    const ballHeight = Array.isArray(event.ball_at) ? Number(event.ball_at[1]) : null
    builder.add({
      ...base,
      category: 'attempt',
      text: `${Who} was in a fielding animation, but the ball never came within reach`
        + `${Number.isFinite(reach) ? ` — it stayed ${reach.toFixed(1)} units away` : ''}`
        + `${Number.isFinite(ballHeight) && ballHeight > 5 ? `, ${ballHeight.toFixed(1)} units overhead` : ''}.`,
      status: 'derived',
      evidence: {
        ...base.evidence,
        closest_reach_units: event.closest_reach_units ?? null,
        within_reach: false,
        why: 'no contact anywhere in the archive was made from further than 6.3 units',
      },
    })
    return
  }
  if (event.ball_contact === 'missed') {
    builder.add({
      ...base,
      category: 'attempt',
      text: `${Who} attempted to field the ball but did not make contact.`,
      status: 'observed',
      evidence: { ...base.evidence, ability_resolution: ability },
    })
    return
  }
  builder.add({
    ...base,
    category: 'attempt',
    text: `The tracker detected an attempt by ${who} but could not determine whether contact occurred.`,
    status: 'unknown',
    evidence: { ...base.evidence, ability_resolution: ability },
  })
}

function describeFielding(builder, { atBat, play }) {
  if (!play) return
  const events = [...(play.fielding_events || [])].sort((a, b) => (a.t ?? 0) - (b.t ?? 0))
  const approaches = (play.catch_approaches || []).filter((approach) => {
    if (!(approach.dive || approach.leap || Number(approach.catch_type) === 5)) return false
    return !events.some((event) => event.by === approach.by && (
      event.approach_start_frame === approach.start_frame
      || (event.frame >= approach.start_frame && event.frame <= approach.end_frame + 2)
      || (event.action_start_frame >= approach.start_frame
        && event.action_start_frame <= approach.end_frame + 2)
    ))
  }).map((approach) => ({
    ...approach,
    event_type: 'fielding_action',
    fielding_attempt: true,
    ball_contact: 'missed',
    secured: false,
    mechanic: 'ordinary',
    official_error: null,
    confidence: 'high',
    contact_source: 'catch_approach_without_contact_or_possession',
    t: approach.start_t ?? null,
    frame: approach.start_frame ?? null,
    action_code: null,
    action_start_frame: approach.start_frame ?? null,
    action_end_frame: approach.end_frame ?? null,
  }))
  const observations = [...events, ...approaches].sort((a, b) => (a.t ?? 0) - (b.t ?? 0))
  for (const event of observations) describeFieldingEvent(builder, event, { play, atBat })

  // A FIELDER THE GAME FROZE. This is measured, not inferred: the fielder
  // struct carries a flag that is up for exactly the 120 frames he cannot
  // move, and it appears at Peach Ice Garden and at no other park. The
  // sentence therefore states the state and stops -- it says a fielder was
  // held, not that a Freezie held him, because the object that did it is not
  // in the captured region and naming it would be a guess. It matters to the
  // reader for the same reason it matters to the metrics: two seconds of a
  // fielder standing still is not a bad route.
  // DK JUNGLE'S FLOWER GAS. Unlike the freeze below, this one NAMES its cause,
  // and the difference is evidence rather than confidence. The Freezie flag says
  // a fielder was held and the object that did it was never captured. This flag
  // fires at all four hand-annotated flower sprays in a session recorded before
  // it was found, at NEITHER annotated barrel hit, and on two fielders at once
  // for the play the operator described that way. At THIS park that is a
  // flower. The flag is not park-exclusive the way the Freezie flag is -- Daisy
  // Cruiser fires it too, unlabelled -- so the sentence is gated on the play
  // being at DK Jungle and says nothing about what it means elsewhere.
  for (const spray of play.flower_sprays || []) {
    const who = fielderPhrase(spray.character, spray.by, atBat)
    const seconds = Number(spray.seconds)
    builder.add({
      category: 'mechanic',
      text: `${capitalized(who)} was caught in the flower gas`
        + (Number.isFinite(seconds) && seconds > 0
          ? ` for ${seconds.toFixed(1)} s` : '')
        + ', and was dazed rather than beaten to the ball.',
      status: 'observed',
      source: 'player_tracking_play.flower_sprays[] (fielder +0x242)',
      evidence: {
        ...spray,
        why: 'measured gas flag on the fielder actor; DK Jungle only, and absent '
          + 'from every labelled barrel hit',
      },
      t: spray.t ?? null,
      frame: null,
    })
  }

  // THE CLOSE PLAY, and who won it. MSS runs an A/B button-mash contest when a
  // runner and a throw reach a base together, and `fielder+0x246` is the
  // fielder's side of it. Unlike the freeze and the knockback above, this one
  // NAMES its outcome: the flag's value is 1 when the fielder held on and 2
  // when the runner knocked the ball loose, which was read off the game's own
  // outs counter and not inferred from the motion. `won_by` is null for any
  // value that has never been observed, and then the sentence says only that
  // there was a contest.
  for (const contest of play.close_plays || []) {
    const who = fielderPhrase(contest.character, contest.by, atBat)
    const wonByRunner = contest.won_by === 'runner'
    const wonByFielder = contest.won_by === 'fielder'
    builder.add({
      category: 'mechanic',
      text: `${capitalized(who)} was in a close play`
        + (wonByRunner
          ? ' and lost it; the runner knocked the ball out of their hands, '
            + 'which is the contest and not a fielding mistake.'
          : wonByFielder
            ? ' and won it; the runner was retired.'
            : '; the capture does not say who won.'),
      status: 'observed',
      source: 'player_tracking_play.close_plays[] (fielder +0x246)',
      evidence: {
        ...contest,
        why: 'measured close-play flag on the fielder actor; the value separates '
          + 'the two outcomes and matched the outs counter on 8 of 8 onsets',
      },
      t: contest.t ?? null,
      frame: contest.frame ?? null,
    })
  }

  for (const freeze of play.freezes || []) {
    const who = fielderPhrase(freeze.character, freeze.by, atBat)
    builder.add({
      category: 'mechanic',
      text: `${capitalized(who)} was frozen for ${Number(freeze.seconds).toFixed(1)} s `
        + 'and could not move; no route or reaction is measured for them on this play.',
      status: 'observed',
      source: 'player_tracking_play.freezes[]',
      evidence: {
        ...freeze,
        why: 'measured freeze flag on the fielder actor; the capture does not name what froze them',
      },
      t: freeze.t ?? null,
      frame: null,
    })
  }

  // Ball Dash has no move to witness -- a mapped character just runs faster
  // while holding the ball -- so the sentence reports the CARRY, which was
  // measured, and names the ability as the passive it is. Saying "used Ball
  // Dash" claimed an activation that does not exist in the game.
  for (const carry of play.possession_carries || []) {
    const who = fielderPhrase(carry.character, carry.by, atBat)
    const speed = Number(carry.peak_speed_ups)

    // Something moved the fielder, and it was not the fielder. Reported because
    // it is measured and because the alternative was silence: the same ground,
    // covered by a Ball Dash character, used to read as a carry.
    //
    // WHAT PUSHED THEM IS NAMED when the capture says so. A knockback is an
    // impulse delivered to a fielder who is HOLDING THE BALL, and possession
    // begins on an exact frame, so the derivation sets `impulse` where the
    // batted ball or a throw arrived on precisely that frame, or where the
    // knockdown flag fired. It stays null when nothing lines up and the
    // sentence still declines to guess -- which is the case this clause was
    // written to protect, and is now the exception rather than every play.
    if (carry.motion === 'knockback') {
      const displacement = Number(carry.displacement_units ?? carry.distance_units)
      // Below the one-unit floor the rest of the narrative already uses this is
      // the recoil of taking the ball, not an event. "Driven back 0.1 units"
      // was noise wearing the clothes of an observation.
      if (!(displacement >= KNOCKBACK_NARRATIVE_FLOOR_UNITS)) continue
      const leaping = carry.impulse === 'leap'
      const pushedBy = KNOCKBACK_IMPULSE_PHRASE[carry.impulse] || null
      builder.add({
        category: 'mechanic',
        text: leaping
          ? `${capitalized(who)} carried ${displacement.toFixed(1)} units past the catch `
            + 'on their own leap rather than being driven back by the ball.'
          : `${capitalized(who)} was driven back `
            + `${displacement.toFixed(1)} units `
            + 'while holding the ball rather than running with it'
            + (pushedBy ? `; ${pushedBy}.` : '; the capture does not say what pushed them.'),
        status: 'derived',
        source: 'player_tracking_play.possession_carries[].motion + .impulse',
        evidence: {
          ...carry,
          why: 'fastest on the first frame, never sped up again, and dead straight',
          cause: leaping
            ? LEAP_CARRY_EVIDENCE
            : carry.impulse
              ? `${carry.impulse}, measured arriving on frame ${carry.impulse_frame}`
              : 'not captured; nothing arrived on the frame the impulse began',
        },
        t: carry.start_t ?? null,
        frame: carry.start_frame ?? null,
      })
      continue
    }

    const ability = resolveCarryAbility({
      characterName: carry.character,
      distanceUnits: carry.distance_units,
      peakSpeedUnitsPerSecond: carry.peak_speed_ups,
      motion: carry.motion,
    })
    if (!ability) continue
    builder.add({
      category: 'ability',
      text: `${who} carried the ball ${Number(carry.distance_units).toFixed(1)} units`
        + `${Number.isFinite(speed) && speed > 0 ? ` at up to ${speed.toFixed(1)} u/s` : ''}`
        + ', with Ball Dash, which is a passive carry-speed bonus rather than a move.',
      status: 'observed',
      source: 'player_tracking_play.possession_carries[] + CHARACTER_FIELDING_ABILITY',
      evidence: { ...ability, carry },
      t: carry.start_t ?? null,
      frame: carry.start_frame ?? null,
    })
  }

  // KNOCKED DOWN BY SOMETHING. `knockdown_flag` is park-neutral and hazard-
  // neutral: it says a fielder was floored and never says by what. Reported
  // only when nothing else on this play already explains it, because where the
  // barrel clause below names the cause, two sentences for one event is worse
  // than one.
  //
  // Zero at Mario Stadium across a full session, which is the park with no
  // gimmicks, and zero at Peach Ice Garden, whose Freezies freeze rather than
  // knock down. Six other parks fire it.
  //
  // AT DK JUNGLE THE BARREL IS NAMED ANYWAY, without the barrel object. The
  // object is not reliably where it was found -- the 2026-09-04 session read
  // zeros at its address for the whole game -- so on that park the flag is the
  // only witness, and it is a good one: the operator annotated three barrel
  // hits and the flag fired on all three. The cause is 'inferred' rather than
  // 'observed' because it is the park's only knockdown hazard rather than
  // something the capture watched, and the DURATION is the measurement.
  const barrelFloored = new Set(
    (play.barrel_events || []).flatMap((barrel) =>
      (barrel.approaches || []).filter((a) => a.hit).map((a) => a.by)),
  )
  const barrelPark = atBat?.hit_stadium_key === 'dk_jungle'
  for (const knock of play.knockdowns || []) {
    if (barrelFloored.has(knock.by)) continue
    const who = fielderPhrase(knock.character, knock.by, atBat)
    const seconds = Number(knock.seconds)
    const forHowLong = Number.isFinite(seconds) && seconds > 0
      ? ` for ${seconds.toFixed(1)} s` : ''
    builder.add({
      category: 'mechanic',
      text: barrelPark
        ? `A barrel knocked ${who} down${forHowLong}.`
        : `${capitalized(who)} was knocked down${forHowLong}`
          + '; the capture does not name what hit them.',
      status: barrelPark ? 'inferred' : 'observed',
      source: 'player_tracking_play.knockdowns[] (fielder +0x23F)',
      evidence: {
        ...knock,
        why: barrelPark
          ? 'measured knockdown flag; the barrel is the only thing at DK Jungle '
            + 'that floors a fielder, and the barrel object itself is not captured'
          : 'measured knockdown flag; it marks the impact and not its cause',
        ...(barrelPark ? { inferred_cause: 'dk_jungle_barrel' } : {}),
      },
      t: knock.t ?? null,
      frame: knock.frame ?? null,
    })
  }

  // DK JUNGLE'S BARREL, the first stadium hazard the capture can actually see.
  // It is narrated only when it REACHED someone: a barrel crossing an empty
  // outfield changed nothing and saying so on every play would bury the ones
  // that mattered. The cause is named here, unlike the knockback clause above,
  // because for once the capture does name it -- the barrel's own position is
  // recorded, and `from_cannon` says which cannon fired it.
  for (const barrel of play.barrel_events || []) {
    for (const approach of barrel.approaches || []) {
      if (!approach.hit) continue
      const who = fielderPhrase(null, approach.by, atBat)
      const moved = Number(approach.fielder_moved_units_after)
      const cannon = barrel.from_cannon ? `${barrel.from_cannon}-side ` : ''
      // SAY THAT THEY WENT DOWN. `hit` is read off the knockdown flag, so a
      // confirmed approach IS a floored fielder -- and this sentence used to
      // report only how close the barrel came and how far they were nudged,
      // which is the one part of it the operator was not asking about.
      const floored = play.knockdowns?.find((knock) => knock.by === approach.by) || null
      const seconds = Number(floored?.seconds)
      builder.add({
        category: 'mechanic',
        text: `A ${cannon}barrel reached ${who}, closing to `
          + `${Number(approach.closest_units).toFixed(1)} units`
          + (approach.knocked_down
            ? `, and knocked them down${Number.isFinite(seconds) && seconds > 0
              ? ` for ${seconds.toFixed(1)} s` : ''}.`
            : Number.isFinite(moved) && moved > 0
              ? `, and they were moved ${moved.toFixed(1)} units after.`
              : '.'),
        status: 'observed',
        source: 'player_tracking_play.barrel_events[] (0x92AF5490)',
        evidence: {
          ...approach,
          from_cannon: barrel.from_cannon ?? null,
          barrel_distance_units: barrel.distance_units,
          peak_height_units: barrel.peak_height_units,
          why: 'measured barrel position against the fielder; the hit radius is '
            + 'provisional until a labelled barrel is captured',
        },
        t: barrel.start_t ?? null,
        frame: approach.closest_frame ?? null,
      })
    }
  }

  // Two fielders going over the wall together. The tracker log only announces
  // the ones that produced an out, so on a ball that cleared the fence the
  // capture is the only thing that saw the attempt at all.
  for (const jump of play.buddy_jumps || []) {
    const who = fielderPhrase(jump.character, jump.by, atBat)
    builder.add({
      category: 'mechanic',
      text: `${capitalized(who)} went up for a Buddy Jump at the wall.`,
      status: 'observed',
      source: 'player_tracking_play.buddy_jumps[] (fielder buddy_jump_flag)',
      evidence: {
        by: jump.by,
        character: jump.character ?? null,
        buddy_jump_flag: jump.flag,
        frames: jump.frames,
        start_t: jump.start_t,
        end_t: jump.end_t,
        why: 'the flag is set only while the game runs the Buddy Jump; it does not say whether the ball was caught',
      },
      t: jump.start_t ?? null,
      frame: jump.start_frame ?? null,
    })
  }

  // The ball fell in and nobody laid a glove on it. Absence is a fact worth a
  // sentence: silence here reads as missing data rather than as a clean hit.
  if (!observations.length && !(play.buddy_jumps || []).length) {
    if (play.landing) {
      // A FOUL BALL HAS NO FAIR-FIELD ZONE. zoneFor answers with the zone the
      // angle points at, which for a ball struck down the line and called foul
      // is "third base" -- and on a strikeout, where describeContact returns
      // before it can say the ball went foul, that sentence claimed a ball in
      // play the plate appearance never had. Name the foul instead and drop
      // the zone; where the foul came down is not a fielding fact.
      const foul = isFoulPlay(play)
      const zone = foul ? null : zoneFor(directionDegrees(play.landing.at), atBat.trajectory)
      builder.add({
        category: 'attempt',
        text: foul
          ? 'No fielder made a play on the foul ball.'
          : `No fielder made a play on the ball; it landed${zone ? ` in ${zone}` : ''}.`,
        status: 'derived',
        source: 'player_tracking_play.landing with no fielding_events',
        evidence: {
          landing: play.landing,
          fielding_events: 0,
          batted_ball_class: play.batted_ball_class ?? null,
        },
        t: play.landing.t ?? null,
        frame: play.landing.frame ?? null,
      })
    // A HOME RUN LEAVES THE PARK, so no fielder played it and nothing landed
    // inside the field -- that is the shape of the play, not a gap in it.
    // Every one of the 2026-09-04 DK Jungle game's five home runs came back
    // amber on this sentence, which is five reminders to go and look at a play
    // where there is nothing to see.
    } else if (isFairPlay(play) && play.batted_ball_class !== 'home_run') {
      builder.add({
        category: 'attempt',
        text: 'The tracker recorded no fielding attempt and no landing for this ball.',
        status: 'unknown',
        source: 'player_tracking_play',
        evidence: { fielding_events: 0, landing: null, batted_ball_class: play.batted_ball_class },
      })
    }
  }

  // Possession that followed somebody else's failure is a recovery, and the
  // chance it represents was created by the boot rather than by the batter.
  const rebound = play.rebound_catch
  if (rebound) {
    builder.add({
      category: 'recovery',
      text: `${capitalized(positionPhrase(rebound.saved_by))} recovered the ball after `
        + `${positionPhrase(rebound.deflected_by)} could not hold it.`,
      status: 'derived',
      source: 'player_tracking_play.rebound_catch',
      evidence: rebound,
      t: null,
      frame: rebound.catch_frame ?? null,
    })
  }

  // Who the original opportunity belonged to, and why the tracker thinks so.
  if (play.primary_fielder) {
    const reasons = {
      catch: 'they caught it',
      failed_contact: 'they were the first to touch it and did not hold it',
      forced_misplay: "the batter's star ball forced their first contact",
      fielded: 'they fielded it',
      buddy_handoff: 'they secured it and passed it on with a buddy toss',
      closest_at_landing: 'nobody touched it, and they were closest to where it came down',
    }
    builder.add({
      category: 'primary_fielder',
      text: `The tracker charges this ball to ${positionPhrase(play.primary_fielder)}, because ${reasons[play.primary_fielder_reason] || 'of the play sequence'}.`,
      status: 'derived',
      source: 'player_tracking_play.primary_fielder',
      evidence: {
        primary_fielder: play.primary_fielder,
        primary_fielder_reason: play.primary_fielder_reason,
        hang_time_s: play.hang_time_s ?? null,
        fielder: play.fielders?.[play.primary_fielder] ?? null,
      },
    })
  }
}

// --- 5-6. throws, relays and Buddy Throws -----------------------------------

// Possession-to-release past this is the top two per cent of every throw in the
// archive (median 0.70 s, p95 1.43 s, p99 2.94 s over 558 measured throws).
const LONG_HOLD_SECONDS = 2.0

// How near in TIME the runner and the ball have to be for it to be a close
// play. The derivation measures both arrivals and reports the difference as
// `margin_s`, negative when the runner got there first.
//
// This used to be read off the gap in UNITS at the moment the ball arrived,
// which measured the runner's speed as much as the margin: a runner at 12 u/s
// is four units from first a third of a second before reaching it, and a runner
// who beat the throw two seconds ago is 0.8 units from the bag standing still.
// The two tests that were here -- inside three units, still closing two -- ruled
// out the whole of one class each and in peach_ice_garden-20260907T234715Z
// selected disjoint sets, so a game with five close plays narrated none.
//
// Half a second at the observed 12 u/s is six units of running, which is well
// past a slide and comfortably short of the next-nearest play in that session
// (0.75 s).
const CLOSE_PLAY_MARGIN_SECONDS = 0.5

function describeThrows(builder, { play, atBat = null }) {
  if (!play) return
  for (const throwRecord of play.throws || []) {
    const thrower = fielderPhrase(
      throwRecord.thrower_character, throwRecord.thrower_position, atBat)
    const receiver = fielderPhrase(
      throwRecord.receiver_character, throwRecord.receiver_position, atBat)
    const target = throwRecord.target_base ? BASE_PHRASES[throwRecord.target_base] : null
    const throwAbility = resolveThrowingAbility({
      characterName: throwRecord.thrower_character,
      targetBase: throwRecord.target_base,
      buddyThrow: throwRecord.buddy_throw,
      peakSpeedMph: throwRecord.peak_speed_mph,
      // Three-valued on purpose: absent means the session was derived before
      // the flag was named, which is not the same as the game saying no.
      laserThrow: throwRecord.laser_throw ?? null,
    })
    const evidence = {
      sequence: throwRecord.sequence,
      thrower_position: throwRecord.thrower_position,
      receiver_position: throwRecord.receiver_position,
      intended_target_position: throwRecord.intended_target_position,
      target_base: throwRecord.target_base,
      peak_speed_mph: throwRecord.peak_speed_mph,
      median_speed_mps: throwRecord.median_speed_mps,
      release_t: throwRecord.release_t,
      launch_t: throwRecord.launch_t,
      arrival_t: throwRecord.arrival_t,
      outs_recorded: throwRecord.outs_recorded,
      is_relay: throwRecord.is_relay,
      buddy_throw: throwRecord.buddy_throw,
      laser_throw: throwRecord.laser_throw ?? null,
      buddy_freeze_s: throwRecord.buddy_freeze_s,
      buddy_thrower_position: throwRecord.buddy_thrower_position,
      buddy_partner_position: throwRecord.buddy_partner_position,
      quality: throwRecord.quality,
      ability_resolution: throwAbility,
      receiver_distance_from_target_units: throwRecord.receiver_distance_from_target_units ?? null,
      receiver_pulled_off_base: throwRecord.receiver_pulled_off_base === true,
    }

    if (throwRecord.is_throw === false || throwRecord.event_type === 'loose_ball_recovery') {
      const runner = throwRecord.runner_contact?.character
        || throwRecord.runner_at_arrival?.character
        || 'The arriving runner'
      builder.add({
        category: 'fielding',
        text: `${runner} knocked the ball loose from ${thrower}; ${receiver} recovered it.`,
        status: 'derived',
        source: 'player_tracking_play.throws[].event_type=loose_ball_recovery',
        evidence: {
          ...evidence,
          event_type: throwRecord.event_type,
          caused_by_runner_contact: throwRecord.caused_by_runner_contact === true,
          runner_contact: throwRecord.runner_contact ?? null,
        },
        t: throwRecord.arrival_t,
        frame: throwRecord.arrival_frame,
      })
      continue
    }

    if (throwRecord.buddy_throw) {
      const partner = throwRecord.buddy_partner_position
      const buddySpeed = Number(throwRecord.peak_speed_mph)
      builder.add({
        category: 'throw',
        // The speed is measured and worth reading -- it is just not either
        // fielder's arm, which is what the evidence note below says.
        text: `${thrower} and ${partner ? positionPhrase(partner) : 'a chemistry partner'} completed a Buddy Throw to ${receiver}`
          + `${target ? ` at ${target}` : ''}`
          + `${Number.isFinite(buddySpeed) ? ` at ${buddySpeed.toFixed(0)} mph` : ''}.`,
        status: 'observed',
        source: 'player_tracking_play.throws[].buddy_throw',
        evidence: {
          ...evidence,
          note: 'the partner releases the ball, so this velocity is not an arm measurement',
        },
        t: throwRecord.launch_t,
        frame: throwRecord.launch_frame,
      })
    } else {
      const speed = Number(throwRecord.peak_speed_mph)
      builder.add({
        category: 'throw',
        text: `${thrower} threw${throwRecord.is_relay ? ' on' : ''} to ${receiver}`
          + `${target ? ` at ${target}` : ''}`
          + `${throwAbility?.status === 'confirmed' ? ` using ${throwAbility.abilityName}` : ''}`
          + `${Number.isFinite(speed) ? ` at ${speed.toFixed(0)} mph` : ''}.`,
        status: 'derived',
        source: 'player_tracking_play.throws[]',
        evidence,
        t: throwRecord.launch_t,
        frame: throwRecord.launch_frame,
      })
    }

    // The character has the throwing ability and the throw did not show it
    // firing. Said once, plainly, rather than folded into the sentence above as
    // an assertion the capture cannot support.
    if (throwAbility?.status === 'unconfirmed') {
      builder.add({
        category: 'ability',
        text: `${thrower} has ${throwAbility.abilityName}, but nothing in this throw confirms it fired.`,
        status: 'unknown',
        source: 'tracker_abilities.resolveThrowingAbility',
        evidence: { ...evidence, ability_resolution: throwAbility },
        t: throwRecord.launch_t,
        frame: throwRecord.launch_frame,
      })
    }

    const targetDistance = Number(throwRecord.receiver_distance_from_target_units)
    if (throwRecord.receiver_pulled_off_base === true && target && Number.isFinite(targetDistance)) {
      builder.add({
        category: 'throw',
        text: `That inaccurate throw pulled ${receiver} ${targetDistance.toFixed(1)} units away from ${target}.`,
        status: 'derived',
        source: 'player_tracking_play.throws[].receiver_pulled_off_base',
        evidence,
        t: throwRecord.arrival_t,
        frame: throwRecord.arrival_frame,
      })
    }

    // The measured basis for the charge. The charge itself is stated once, in
    // the outcome section, off the plate appearance's own error fields -- so
    // this says what was seen and never what it was scored as.
    if (throwRecord.throwing_error_candidate === true) {
      builder.add({
        category: 'throw',
        text: `That throw let the arriving runner reach ${target} — a wild throw that permitted an advance.`,
        status: 'derived',
        source: 'player_tracking_play.throws[].throwing_error_candidate',
        evidence: {
          ...evidence,
          throwing_error_candidate: true,
          runner_at_arrival: throwRecord.runner_at_arrival ?? null,
          rule: 'OBR 9.12(a)(1)',
        },
        t: throwRecord.arrival_t,
        frame: throwRecord.arrival_frame,
      })
    }

    // HOW LONG THE BALL SAT IN THE GLOVE. Across 558 measured throws the median
    // release is 0.70 s and the 95th percentile 1.43 s, so a hold past two
    // seconds is the top two per cent and something happened. DK Jungle's
    // flower sprays a fielder and leaves them dazed and unable to throw, and
    // the longest hold in that session is exactly the play the operator flagged
    // for it. The delay is measured and reported; the cause is not guessed at,
    // because nothing in the capture names one.
    const hold = Number(throwRecord.hold_s)
    if (Number.isFinite(hold) && hold >= LONG_HOLD_SECONDS) {
      builder.add({
        category: 'throw',
        text: `${thrower} held the ball ${hold.toFixed(1)} s before releasing it; `
          + 'an ordinary throw goes inside 1.5 s.',
        status: 'derived',
        source: 'player_tracking_play.throws[].hold_s',
        evidence: {
          ...evidence,
          hold_s: hold,
          why: 'measured possession-to-release; the capture does not say what caused the delay',
        },
        t: throwRecord.release_t,
        frame: throwRecord.release_frame,
      })
    }

    // HOW CLOSE IT WAS. The ball's arrival frame is measured and so is where
    // every runner stood on it, and a runner still inside the bag's own radius
    // when the throw got there is what an operator means by a close play. Who
    // won it is NOT read off this -- that is the game's call and it is in
    // `outs_recorded` on this same throw; this is only the margin, which
    // nothing else in the capture records.
    const contested = throwRecord.runner_at_arrival
    // `margin_s` is null when the runner never reached that base, which is most
    // throws: the nearest runner to second on a routine grounder to first is
    // twenty units away and was never in the play.
    // `Number(null)` is 0, which is finite -- reading it straight would narrate
    // every uncontested throw in the game as a 0.00 s close play.
    const margin = contested?.margin_s == null ? NaN : Number(contested.margin_s)
    if (contested && target && Number.isFinite(margin)
      && Math.abs(margin) <= CLOSE_PLAY_MARGIN_SECONDS) {
      const runnerName = contested.character && !UNNAMED_CHARACTER.test(contested.character)
        ? contested.character : 'a runner'
      builder.add({
        category: 'throw',
        text: `${capitalized(runnerName)} reached ${target} `
          + `${Math.abs(margin).toFixed(2)} s ${margin < 0 ? 'before' : 'after'} the throw did`
          + `${throwRecord.outs_recorded > 0 ? ', and the out was recorded' : ', and no out was recorded'}.`,
        status: 'derived',
        source: 'player_tracking_play.throws[].runner_at_arrival',
        evidence: {
          ...evidence,
          runner_at_arrival: contested,
          why: 'both arrivals are measured; who won the play is the game call, in outs_recorded',
        },
        t: throwRecord.arrival_t,
        frame: throwRecord.arrival_frame,
      })
    }

    // Intent and outcome are different facts: on a throw to second base the
    // covering middle infielder often takes it, which is coverage rather than a
    // bad throw.
    if (throwRecord.intended_target_position
      && throwRecord.intended_target_position !== throwRecord.receiver_position) {
      builder.add({
        category: 'throw',
        text: `That throw was aimed at ${positionPhrase(throwRecord.intended_target_position)}; `
        + `${positionPhrase(throwRecord.receiver_position)} covered and took it.`,
        status: 'observed',
        source: 'player_tracking_play.throws[].intended_target_position',
        evidence,
      })
    }
    if (throwRecord.outs_recorded > 0) {
      builder.add({
        category: 'outcome',
        text: `${throwRecord.outs_recorded === 1 ? 'An out was' : `${throwRecord.outs_recorded} outs were`} recorded on that throw.`,
        status: 'derived',
        source: 'player_tracking_play.throws[].outs_recorded',
        evidence,
      })
    }
  }
}

// A Buddy Jump is announced by the tracker log, not by the memory capture, so
// it is described from the plate appearance and says which fielders the log
// named.
function describeBuddyJump(builder, { atBat, play = null }) {
  const assist = atBat.buddy_jump_assist_position
  const putout = atBat.buddy_jump_putout_position
  // An attempt the log announced and the capture did not see. When the capture
  // DID see it, its own clause names the fielder and the position, and saying
  // it twice reads as two jumps.
  if (!atBat.is_buddy_jump && !putout) {
    if (!atBat.buddy_jump_attempt_by || (play?.buddy_jumps || []).length) return
    builder.add({
      category: 'mechanic',
      text: `${atBat.buddy_jump_attempt_by} went up for a Buddy Jump, and no out followed.`,
      status: 'observed',
      source: 'tracker log "is going up for a buddy jump!" with no completion line',
      evidence: {
        is_buddy_jump: false,
        buddy_jump_attempt_by: atBat.buddy_jump_attempt_by,
        buddy_jump_putout_position: null,
      },
    })
    return
  }
  if (atBat.is_buddy_jump) {
    builder.add({
      category: 'mechanic',
      text: `A Buddy Jump was completed${assist ? ` with help from position ${assist}` : ''}`
        + `${putout ? `, and position ${putout} made the catch` : ''}.`,
      status: 'observed',
      source: 'tracker log "went high up with the buddy jump to get the out!"',
      evidence: {
        is_buddy_jump: true,
        buddy_jump_assist_position: assist ?? null,
        buddy_jump_putout_position: putout ?? null,
        is_robbed_hr: atBat.is_robbed_hr ?? null,
      },
    })
  } else {
    builder.add({
      category: 'mechanic',
      text: 'A Buddy Jump was attempted and did not produce an out.',
      status: 'observed',
      source: 'tracker log "is going up for a buddy jump!" with no completion line',
      evidence: { is_buddy_jump: false, buddy_jump_putout_position: putout ?? null },
    })
  }
}

// --- 7. outs, runners, runs, and the official result ------------------------

function describeOutcome(builder, { atBat, play }) {
  const result = atBat.result
  if (!result) {
    builder.add({
      category: 'outcome',
      text: 'This plate appearance has not finished.',
      status: 'pending',
      source: 'plate_appearance.result',
      evidence: { result: null, pitches: atBat.pitches?.length ?? 0 },
    })
    return
  }

  const assignments = atBat.runner_assignments || null
  if (assignments) {
    for (const assignment of assignments) {
      const name = assignment.runner?.characterName || 'A runner'
      const origin = assignment.isBatter ? 'the plate' : BASE_PHRASES[assignment.origin] || assignment.origin
      const destination = assignment.destination
      let text
      if (destination === 'out') {
        text = assignment.isBatter ? `${name} was retired.` : `${name} was retired coming from ${origin}.`
      } else if (destination === 'home') {
        text = `${name} scored${assignment.isBatter ? '' : ` from ${origin}`}.`
      } else if (assignment.isBatter) {
        text = `${name} reached ${BASE_PHRASES[destination] || destination}.`
      } else if (destination === assignment.origin) {
        // A runner who finished on the base he started on did not advance. The
        // assignment resolver is right -- he is still there -- but "advanced
        // from first to first" describes a move that cannot happen.
        text = `${name} held at ${origin}.`
      } else {
        text = `${name} advanced from ${origin} to ${BASE_PHRASES[destination] || destination}.`
      }
      const runner = play?.runners?.[assignment.isBatter ? 'BAT' : `R${{ first: 1, second: 2, third: 3 }[assignment.origin]}`] || null
      builder.add({
        category: 'runner',
        text,
        status: 'observed',
        source: 'plate_appearance.runner_assignments[]',
        evidence: {
          runner: name,
          origin: assignment.origin,
          destination,
          is_batter: Boolean(assignment.isBatter),
          bases_ran: runner?.bases_ran ?? null,
          sprint_speed_ups: runner?.sprint_speed_ups ?? null,
          lead_at_contact_units: runner?.lead_at_contact_units ?? null,
          stealing: runner?.stealing ?? null,
          home_to_first_s: assignment.isBatter ? play?.home_to_first_s ?? null : null,
          ninety_foot_split_s: assignment.isBatter ? play?.ninety_foot_split_s ?? null : null,
        },
      })
    }
  } else if (atBat.runners_before
    && (atBat.runners_before.first || atBat.runners_before.second || atBat.runners_before.third)) {
    builder.add({
      category: 'runner',
      text: 'The tracker could not resolve where every runner finished on this play.',
      status: 'unknown',
      source: 'plate_appearance.runner_assignments',
      evidence: { runners_before: atBat.runners_before, runner_assignments: null },
    })
  }

  const runs = atBat.runs_scored || []
  if (runs.length) {
    builder.add({
      category: 'outcome',
      text: `${runs.length} run${runs.length === 1 ? '' : 's'} scored on the play`
        + `${atBat.rbi ? `, with ${atBat.rbi} RBI credited to ${atBat.batter_name}` : ''}.`,
      status: 'observed',
      source: 'plate_appearance.runs_scored[]',
      evidence: { runs_scored: runs, rbi: atBat.rbi },
    })
  }

  const phrase = RESULT_PHRASES[result] || `a ${result}`
  const outs = Number(atBat.outs_on_play || 0)
  builder.add({
    category: 'outcome',
    text: `The plate appearance is scored as ${phrase}`
      + `${outs ? `, ${outs} out${outs === 1 ? '' : 's'} on the play` : ''}.`,
    status: 'observed',
    source: 'plate_appearance.result',
    evidence: {
      result,
      outs_on_play: outs,
      is_official_ab: atBat.is_official_ab,
      hit_notation: atBat.hit_notation,
      is_error: atBat.is_error,
      error_character: atBat.error_character,
      error_position: atBat.error_position,
      fielder_choice_out: atBat.fielder_choice_out,
    },
  })

  // An operator who just watched the tracker print "X bobbled the ball!" needs
  // to be told why no error followed it. Silence here reads as a dropped
  // charge rather than as a ruling, which is the one thing the console exists
  // to prevent.
  if (!atBat.is_error && atBat.error_vetoed_reason) {
    builder.add({
      category: 'scoring',
      text: `The tracker reported a bobble by ${atBat.fielding_events?.bobble || 'a fielder'}, `
        + `and no error is charged: ${atBat.error_vetoed_detail}.`,
      status: 'derived',
      source: 'tracker_play_events.trackerBobbleErrorVeto',
      evidence: {
        bobble: atBat.fielding_events?.bobble ?? null,
        vetoed_reason: atBat.error_vetoed_reason,
        vetoed_detail: atBat.error_vetoed_detail,
        why: 'an error requires a ball the fielder could have handled with ordinary effort',
      },
    })
  }

  // The official error is the scorer's call, and the tracker only has one when
  // its log said so. That is a different claim from a fielder not holding the
  // ball, and the two are never merged.
  if (atBat.is_error) {
    // The measured throwing error has no announcement behind it, so it says
    // which kind it is and where the ruling came from. An operator who saw the
    // tracker print nothing must not be left reading it as a log-scored boot.
    const throwing = atBat.error_kind === 'throwing'
    builder.add({
      category: 'scoring',
      text: `${throwing ? 'A throwing error' : 'An error'} is charged to ${atBat.error_character || 'the fielder'}`
        + `${atBat.error_position ? ` at position ${atBat.error_position}` : ''}`
        + `${throwing ? ', from the capture’s own measurement of the throw' : ''}.`,
      status: 'observed',
      source: throwing
        ? 'player_tracking_play.throws[].throwing_error_candidate scored under OBR 9.12(a)(1)'
        : 'tracker log "bobbled the ball!" scored as an error',
      evidence: {
        is_error: true,
        error_kind: atBat.error_kind ?? null,
        error_character: atBat.error_character,
        error_position: atBat.error_position,
        error_notation: atBat.error_notation,
        bobble: atBat.fielding_events?.bobble ?? null,
      },
    })
  }

  const star = resolveStarAbility({
    characterName: atBat.pitcher_name, used: Boolean(atBat.star_pitch_used), kind: 'pitch',
  })
  if (star.status === 'confirmed') {
    builder.add({
      category: 'ability',
      text: `${atBat.pitcher_name} used ${star.abilityName} in this plate appearance.`,
      status: 'observed',
      source: 'tracker log "used a star pitch!" + CHARACTER_STAR_PITCH',
      evidence: { ...star, star_pitch_used: true, star_pitch_successful: atBat.star_pitch_successful },
    })
  } else if (star.status === 'unresolved') {
    builder.add({
      category: 'ability',
      text: `${atBat.pitcher_name} used a star pitch. The roster does not name which pitch that is.`,
      status: 'unknown',
      source: 'tracker log "used a star pitch!"',
      evidence: { ...star, star_pitch_used: true },
    })
  }
}

// --- unresolved/mismatched ability notes ------------------------------------
//
// Routine plays stay routine. Only a contradictory approach or an unresolved
// special action needs a caveat; listing every unused roster capability made
// ordinary pickups sound like failed ability activations.

function describeAbilityCaveats(builder, { play, atBat = null }) {
  if (!play) return
  const seen = new Set()
  for (const event of play.fielding_events || []) {
    const character = namedFielder(event.character, event.by, atBat)
    if (!character || seen.has(character)) continue
    const ability = resolveFieldingAbility({
      characterName: character, actionCode: event.action_code,
      catchType: event.catch_type ?? null,
      observedDive: event.dive === true,
      observedLeap: event.leap === true,
    })
    // A confirmed activation was already narrated where it happened, and a
    // caveat denying it would contradict the sentence above it. The character
    // is only marked seen once something has been said about them, so a plain
    // first touch does not suppress a real activation later in the play.
    if (ability.status === 'confirmed') { seen.add(character); continue }
    seen.add(character)
    if (ability.status === 'mismatch') {
      builder.add({
        category: 'ability',
        text: `${character} used the ${ability.observedAbilityName} approach, which the roster says `
          + `they do not have${ability.mappedAbility ? ` (they map to ${ability.mappedAbility})` : ''}.`,
        status: 'mismatch',
        source: 'player_tracking_play.fielding_events[].catch_type',
        evidence: { ...ability, character },
      })
    } else if (ability.status === 'unresolved') {
      builder.add({
        category: 'ability',
        text: `${character} triggered a special fielding action the tracker cannot yet name`
          + `${ability.mappedAbility ? ` (their mapped ability is ${ability.mappedAbility})` : ''}.`,
        status: 'unknown',
        source: 'player_tracking_play.fielding_events[].action_code',
        evidence: { ...ability, character },
      })
    }
  }
}

// --- assembly ---------------------------------------------------------------

function summarize(atBat, play, clauses) {
  const result = atBat?.result
  const label = result ? (RESULT_PHRASES[result] || result) : 'in progress'
  const lead = clauses.find((clause) => clause.category === 'contact')
  if (lead) return `${lead.text.replace(/\.$/, '')} — ${label}.`
  return `${atBat?.batter_name || 'Batter'} vs ${atBat?.pitcher_name || 'pitcher'} — ${label}.`
}

/**
 * Build the tracker's interpretation of one plate appearance.
 *
 * `play` is the joined 60 Hz player-tracking play, or null when none is
 * joined. `join` is the join result, whose status decides whether the
 * fielding half of the narrative can be trusted at all -- an ambiguous or
 * orphaned play is deliberately NOT narrated, because a fielding sequence
 * attached to the wrong at-bat is the most convincing wrong answer this whole
 * system can produce.
 */
export function buildTrackerNarrative({
  atBat = null, play = null, join = null, captureStatus = null,
} = {}) {
  if (!atBat) {
    return {
      status: 'unavailable',
      summary: 'No at-bat to interpret yet.',
      sentences: [],
      clauses: [],
      timeline: [],
      join: join || null,
    }
  }

  const joinStatus = join?.status || (play ? 'joined' : 'pending')
  const usablePlay = play && joinStatus === 'joined' ? play : null

  const builder = new NarrativeBuilder()
  describeContact(builder, { atBat, play: usablePlay })
  describeBatterStarSwing(builder, { atBat })
  describeFielding(builder, { atBat, play: usablePlay })
  describeBuddyJump(builder, { atBat, play: usablePlay })
  describeThrows(builder, { play: usablePlay, atBat })
  describeOutcome(builder, { atBat, play: usablePlay })
  describeAbilityCaveats(builder, { play: usablePlay, atBat })

  // Why the fielding half is missing, when it is. Silence would read as "no
  // fielder was involved", which is a different and much worse claim.
  if (!usablePlay) {
    // "Not yet" and "never" look identical on screen and are completely
    // different facts. A session with no collector running will never produce a
    // play, and saying it is pending sends an operator looking for a delay that
    // does not exist.
    const noCollector = captureStatus === 'disabled' || captureStatus === 'failed'
    const messages = {
      pending: noCollector
        ? (captureStatus === 'failed'
          ? 'The 60 Hz collector failed for this session, so there is no fielding, route or throw detail and none is coming. The tracker log half of this at-bat is unaffected.'
          : 'No 60 Hz collector is running for this session, so there is no fielding, route or throw detail. Start the bridge (npm run tracker:bridge) rather than the standalone preview to capture it.')
        : 'The 60 Hz player-tracking play for this at-bat has not arrived yet, so no fielding, route or throw detail is available.',
      ambiguous: 'A 60 Hz play could belong to this at-bat or to another one, so none has been attached. Fielding detail is withheld rather than guessed.',
      orphaned: 'A 60 Hz play was derived that matches no at-bat in this session.',
      mismatch: 'The 60 Hz play that matches this at-bat contradicts it, so its fielding detail is withheld.',
      joined: 'No 60 Hz player-tracking play was derived for this at-bat.',
    }
    builder.add({
      category: 'join',
      text: messages[joinStatus] || messages.pending,
      // A collector that is not running is not a pending fact, it is an absent
      // one, and the clause is coloured accordingly.
      status: joinStatus === 'mismatch' ? 'mismatch'
        : joinStatus === 'pending' ? (noCollector ? 'not_applicable' : 'pending')
          : 'unknown',
      source: noCollector
        ? 'tracker_preview_state.capture.status'
        : 'tracker_play_join.joinPlayToAtBat',
      evidence: { ...(join || { status: joinStatus }), capture_status: captureStatus },
    })
  }

  const clauses = builder.clauses
  const status = !atBat.result ? 'pending'
    : usablePlay ? 'complete'
      : 'partial'

  return {
    status,
    summary: summarize(atBat, usablePlay, clauses),
    sentences: clauses.map((clause) => clause.text),
    clauses,
    timeline: builder.timeline.sort((a, b) => {
      const left = a.frame ?? Number.MAX_SAFE_INTEGER
      const right = b.frame ?? Number.MAX_SAFE_INTEGER
      return left - right
    }),
    join: join || { status: joinStatus },
    play_contact_timer: usablePlay?.contact_timer ?? null,
  }
}
