alter table characters
  add column if not exists slap_contact integer default 60,
  add column if not exists charge_contact integer default 40,
  add column if not exists slap_power integer default 30,
  add column if not exists charge_power integer default 50,
  add column if not exists bunting integer default 30,
  add column if not exists run_speed integer default 50,
  add column if not exists throwing_speed integer default 50,
  add column if not exists fielding_stat integer default 50,
  add column if not exists curveball_speed integer default 110,
  add column if not exists fastball_speed integer default 130,
  add column if not exists curve integer default 40,
  add column if not exists stamina integer default 60,
  add column if not exists star_boost_pct integer default 50,
  add column if not exists hitting_trajectory text default 'Medium',
  add column if not exists character_class text default 'Balanced',
  add column if not exists is_captain boolean default false;

update characters set slap_contact=75, charge_contact=55, slap_power=50, charge_power=70, bunting=30, run_speed=70, throwing_speed=70, fielding_stat=60, curveball_speed=122, fastball_speed=139, curve=70, stamina=87, star_boost_pct=50, hitting_trajectory='Medium', character_class='Balanced', is_captain=true where name='Mario';
update characters set slap_contact=70, charge_contact=50, slap_power=40, charge_power=60, bunting=30, run_speed=70, throwing_speed=60, fielding_stat=70, curveball_speed=124, fastball_speed=138, curve=60, stamina=70, star_boost_pct=50, hitting_trajectory='Medium', character_class='Speed', is_captain=true where name='Luigi';
update characters set slap_contact=50, charge_contact=30, slap_power=60, charge_power=90, bunting=10, run_speed=20, throwing_speed=85, fielding_stat=30, curveball_speed=136, fastball_speed=150, curve=30, stamina=90, star_boost_pct=50, hitting_trajectory='High', character_class='Power', is_captain=true where name='Donkey Kong';
update characters set slap_contact=65, charge_contact=45, slap_power=20, charge_power=40, bunting=40, run_speed=65, throwing_speed=40, fielding_stat=84, curveball_speed=125, fastball_speed=134, curve=55, stamina=65, star_boost_pct=50, hitting_trajectory='Medium', character_class='Technique', is_captain=true where name='Diddy Kong';
update characters set slap_contact=80, charge_contact=60, slap_power=20, charge_power=40, bunting=50, run_speed=50, throwing_speed=40, fielding_stat=80, curveball_speed=121, fastball_speed=130, curve=80, stamina=63, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=true where name='Peach';
update characters set slap_contact=70, charge_contact=50, slap_power=40, charge_power=60, bunting=40, run_speed=50, throwing_speed=60, fielding_stat=80, curveball_speed=124, fastball_speed=140, curve=65, stamina=66, star_boost_pct=50, hitting_trajectory='Medium', character_class='Power', is_captain=true where name='Daisy';
update characters set slap_contact=55, charge_contact=35, slap_power=30, charge_power=45, bunting=40, run_speed=90, throwing_speed=40, fielding_stat=55, curveball_speed=126, fastball_speed=135, curve=40, stamina=60, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=true where name='Yoshi';
update characters set slap_contact=45, charge_contact=25, slap_power=65, charge_power=98, bunting=10, run_speed=29, throwing_speed=98, fielding_stat=32, curveball_speed=140, fastball_speed=152, curve=13, stamina=100, star_boost_pct=50, hitting_trajectory='High', character_class='Power', is_captain=true where name='Bowser';
update characters set slap_contact=60, charge_contact=40, slap_power=50, charge_power=80, bunting=10, run_speed=40, throwing_speed=80, fielding_stat=30, curveball_speed=132, fastball_speed=147, curve=35, stamina=98, star_boost_pct=50, hitting_trajectory='Medium', character_class='Technique', is_captain=true where name='Wario';
update characters set slap_contact=5, charge_contact=80, slap_power=90, charge_power=1, bunting=50, run_speed=50, throwing_speed=40, fielding_stat=80, curveball_speed=130, fastball_speed=90, curve=80, stamina=59, star_boost_pct=50, hitting_trajectory='Medium', character_class='Technique', is_captain=true where name='Waluigi';
update characters set slap_contact=60, charge_contact=40, slap_power=48, charge_power=78, bunting=20, run_speed=50, throwing_speed=80, fielding_stat=70, curveball_speed=132, fastball_speed=147, curve=38, stamina=88, star_boost_pct=50, hitting_trajectory='Medium', character_class='Power', is_captain=true where name='Birdo';
update characters set slap_contact=75, charge_contact=55, slap_power=50, charge_power=70, bunting=20, run_speed=70, throwing_speed=68, fielding_stat=42, curveball_speed=95, fastball_speed=135, curve=37, stamina=83, star_boost_pct=50, hitting_trajectory='Medium', character_class='Technique', is_captain=true where name='Bowser Jr.';
update characters set slap_contact=60, charge_contact=40, slap_power=20, charge_power=30, bunting=40, run_speed=80, throwing_speed=30, fielding_stat=40, curveball_speed=110, fastball_speed=118, curve=60, stamina=46, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Baby Mario';
update characters set slap_contact=55, charge_contact=35, slap_power=10, charge_power=20, bunting=40, run_speed=80, throwing_speed=20, fielding_stat=50, curveball_speed=109, fastball_speed=119, curve=60, stamina=45, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Baby Luigi';
update characters set slap_contact=70, charge_contact=50, slap_power=30, charge_power=50, bunting=30, run_speed=64, throwing_speed=50, fielding_stat=45, curveball_speed=121, fastball_speed=138, curve=50, stamina=56, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Koopa';
update characters set slap_contact=55, charge_contact=35, slap_power=30, charge_power=50, bunting=30, run_speed=70, throwing_speed=50, fielding_stat=30, curveball_speed=114, fastball_speed=140, curve=47, stamina=52, star_boost_pct=50, hitting_trajectory='High', character_class='Speed', is_captain=false where name='Red Toad';
update characters set slap_contact=75, charge_contact=55, slap_power=20, charge_power=30, bunting=40, run_speed=44, throwing_speed=30, fielding_stat=32, curveball_speed=112, fastball_speed=132, curve=89, stamina=43, star_boost_pct=50, hitting_trajectory='Medium', character_class='Speed', is_captain=false where name='Boo';
update characters set slap_contact=70, charge_contact=50, slap_power=20, charge_power=30, bunting=30, run_speed=80, throwing_speed=30, fielding_stat=40, curveball_speed=122, fastball_speed=128, curve=53, stamina=41, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=false where name='Toadette';
update characters set slap_contact=60, charge_contact=40, slap_power=35, charge_power=55, bunting=44, run_speed=45, throwing_speed=55, fielding_stat=70, curveball_speed=116, fastball_speed=130, curve=42, stamina=62, star_boost_pct=50, hitting_trajectory='Low', character_class='Technique', is_captain=false where name='Shy Guy';
update characters set slap_contact=50, charge_contact=30, slap_power=20, charge_power=30, bunting=30, run_speed=20, throwing_speed=40, fielding_stat=80, curveball_speed=119, fastball_speed=125, curve=81, stamina=31, star_boost_pct=50, hitting_trajectory='Medium', character_class='Balanced', is_captain=false where name='Magikoopa';
update characters set slap_contact=55, charge_contact=35, slap_power=25, charge_power=35, bunting=30, run_speed=14, throwing_speed=40, fielding_stat=80, curveball_speed=119, fastball_speed=125, curve=81, stamina=31, star_boost_pct=50, hitting_trajectory='Medium', character_class='Balanced', is_captain=false where name='Red Magikoopa';
update characters set slap_contact=50, charge_contact=30, slap_power=20, charge_power=30, bunting=30, run_speed=25, throwing_speed=40, fielding_stat=80, curveball_speed=99, fastball_speed=105, curve=77, stamina=31, star_boost_pct=50, hitting_trajectory='Medium', character_class='Balanced', is_captain=false where name='Green Magikoopa';
update characters set slap_contact=55, charge_contact=35, slap_power=25, charge_power=35, bunting=30, run_speed=20, throwing_speed=40, fielding_stat=80, curveball_speed=99, fastball_speed=105, curve=77, stamina=31, star_boost_pct=50, hitting_trajectory='Medium', character_class='Balanced', is_captain=false where name='Yellow Magikoopa';
update characters set slap_contact=65, charge_contact=45, slap_power=50, charge_power=70, bunting=20, run_speed=40, throwing_speed=70, fielding_stat=30, curveball_speed=108, fastball_speed=122, curve=75, stamina=49, star_boost_pct=50, hitting_trajectory='Medium', character_class='Power', is_captain=false where name='King Boo';
update characters set slap_contact=45, charge_contact=25, slap_power=62, charge_power=92, bunting=10, run_speed=20, throwing_speed=90, fielding_stat=48, curveball_speed=150, fastball_speed=175, curve=5, stamina=20, star_boost_pct=50, hitting_trajectory='High', character_class='Power', is_captain=false where name='Petey Piranha';
update characters set slap_contact=60, charge_contact=40, slap_power=20, charge_power=35, bunting=30, run_speed=72, throwing_speed=40, fielding_stat=80, curveball_speed=120, fastball_speed=130, curve=30, stamina=48, star_boost_pct=50, hitting_trajectory='Medium', character_class='Balanced', is_captain=false where name='Dixie Kong';
update characters set slap_contact=60, charge_contact=40, slap_power=20, charge_power=40, bunting=90, run_speed=40, throwing_speed=50, fielding_stat=60, curveball_speed=90, fastball_speed=95, curve=42, stamina=61, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Goomba';
update characters set slap_contact=60, charge_contact=40, slap_power=20, charge_power=40, bunting=50, run_speed=50, throwing_speed=45, fielding_stat=65, curveball_speed=110, fastball_speed=122, curve=47, stamina=58, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=false where name='Paragoomba';
update characters set slap_contact=60, charge_contact=25, slap_power=10, charge_power=85, bunting=10, run_speed=30, throwing_speed=85, fielding_stat=55, curveball_speed=128, fastball_speed=147, curve=20, stamina=69, star_boost_pct=50, hitting_trajectory='High', character_class='Power', is_captain=false where name='Hammer Bro';
update characters set slap_contact=65, charge_contact=45, slap_power=20, charge_power=30, bunting=50, run_speed=35, throwing_speed=60, fielding_stat=78, curveball_speed=70, fastball_speed=80, curve=20, stamina=33, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=false where name='Toadsworth';
update characters set slap_contact=60, charge_contact=40, slap_power=50, charge_power=70, bunting=20, run_speed=35, throwing_speed=75, fielding_stat=70, curveball_speed=118, fastball_speed=142, curve=31, stamina=68, star_boost_pct=50, hitting_trajectory='High', character_class='Power', is_captain=false where name='Kritter';
update characters set slap_contact=55, charge_contact=35, slap_power=45, charge_power=65, bunting=20, run_speed=35, throwing_speed=75, fielding_stat=70, curveball_speed=114, fastball_speed=146, curve=31, stamina=68, star_boost_pct=50, hitting_trajectory='High', character_class='Power', is_captain=false where name='Blue Kritter';
update characters set slap_contact=55, charge_contact=35, slap_power=55, charge_power=75, bunting=20, run_speed=35, throwing_speed=75, fielding_stat=70, curveball_speed=122, fastball_speed=138, curve=24, stamina=68, star_boost_pct=50, hitting_trajectory='High', character_class='Power', is_captain=false where name='Red Kritter';
update characters set slap_contact=55, charge_contact=35, slap_power=50, charge_power=70, bunting=20, run_speed=40, throwing_speed=75, fielding_stat=70, curveball_speed=122, fastball_speed=138, curve=24, stamina=68, star_boost_pct=50, hitting_trajectory='High', character_class='Power', is_captain=false where name='Brown Kritter';
update characters set slap_contact=70, charge_contact=18, slap_power=64, charge_power=94, bunting=10, run_speed=10, throwing_speed=90, fielding_stat=20, curveball_speed=135, fastball_speed=155, curve=48, stamina=38, star_boost_pct=50, hitting_trajectory='High', character_class='Power', is_captain=false where name='King K. Rool';
update characters set slap_contact=70, charge_contact=55, slap_power=15, charge_power=25, bunting=50, run_speed=60, throwing_speed=30, fielding_stat=50, curveball_speed=105, fastball_speed=117, curve=80, stamina=30, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=false where name='Baby Peach';
update characters set slap_contact=70, charge_contact=50, slap_power=20, charge_power=40, bunting=50, run_speed=60, throwing_speed=40, fielding_stat=50, curveball_speed=115, fastball_speed=122, curve=65, stamina=35, star_boost_pct=50, hitting_trajectory='Low', character_class='Power', is_captain=false where name='Baby Daisy';
update characters set slap_contact=55, charge_contact=40, slap_power=50, charge_power=65, bunting=55, run_speed=40, throwing_speed=70, fielding_stat=82, curveball_speed=118, fastball_speed=132, curve=30, stamina=47, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Baby DK';
update characters set slap_contact=55, charge_contact=35, slap_power=50, charge_power=70, bunting=20, run_speed=75, throwing_speed=70, fielding_stat=42, curveball_speed=128, fastball_speed=142, curve=27, stamina=82, star_boost_pct=50, hitting_trajectory='High', character_class='Speed', is_captain=false where name='Wiggler';
update characters set slap_contact=70, charge_contact=50, slap_power=30, charge_power=50, bunting=60, run_speed=50, throwing_speed=50, fielding_stat=50, curveball_speed=100, fastball_speed=112, curve=46, stamina=57, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=false where name='Blooper';
update characters set slap_contact=60, charge_contact=30, slap_power=50, charge_power=80, bunting=10, run_speed=30, throwing_speed=80, fielding_stat=60, curveball_speed=142, fastball_speed=110, curve=22, stamina=85, star_boost_pct=50, hitting_trajectory='High', character_class='Power', is_captain=false where name='Funky Kong';
update characters set slap_contact=68, charge_contact=50, slap_power=30, charge_power=50, bunting=50, run_speed=55, throwing_speed=40, fielding_stat=75, curveball_speed=126, fastball_speed=135, curve=54, stamina=64, star_boost_pct=50, hitting_trajectory='Medium', character_class='Balanced', is_captain=false where name='Tiny Kong';
update characters set slap_contact=65, charge_contact=45, slap_power=55, charge_power=75, bunting=20, run_speed=50, throwing_speed=70, fielding_stat=41, curveball_speed=128, fastball_speed=142, curve=41, stamina=44, star_boost_pct=50, hitting_trajectory='High', character_class='Balanced', is_captain=false where name='Dry Bones';
update characters set slap_contact=65, charge_contact=45, slap_power=55, charge_power=75, bunting=20, run_speed=50, throwing_speed=70, fielding_stat=38, curveball_speed=125, fastball_speed=147, curve=46, stamina=44, star_boost_pct=50, hitting_trajectory='High', character_class='Balanced', is_captain=false where name='Dark Bones';
update characters set slap_contact=65, charge_contact=45, slap_power=55, charge_power=75, bunting=20, run_speed=57, throwing_speed=70, fielding_stat=41, curveball_speed=128, fastball_speed=137, curve=37, stamina=44, star_boost_pct=50, hitting_trajectory='High', character_class='Balanced', is_captain=false where name='Green Dry Bones';
update characters set slap_contact=65, charge_contact=45, slap_power=55, charge_power=75, bunting=20, run_speed=50, throwing_speed=70, fielding_stat=49, curveball_speed=128, fastball_speed=137, curve=37, stamina=44, star_boost_pct=50, hitting_trajectory='High', character_class='Balanced', is_captain=false where name='Blue Dry Bones';
update characters set slap_contact=55, charge_contact=20, slap_power=10, charge_power=88, bunting=10, run_speed=30, throwing_speed=85, fielding_stat=55, curveball_speed=132, fastball_speed=150, curve=15, stamina=69, star_boost_pct=50, hitting_trajectory='High', character_class='Power', is_captain=false where name='Fire Bro';
update characters set slap_contact=55, charge_contact=20, slap_power=10, charge_power=85, bunting=10, run_speed=30, throwing_speed=80, fielding_stat=50, curveball_speed=128, fastball_speed=147, curve=63, stamina=69, star_boost_pct=50, hitting_trajectory='Medium', character_class='Power', is_captain=false where name='Boomerang Bro';
update characters set slap_contact=55, charge_contact=35, slap_power=52, charge_power=82, bunting=20, run_speed=20, throwing_speed=80, fielding_stat=35, curveball_speed=132, fastball_speed=147, curve=32, stamina=67, star_boost_pct=50, hitting_trajectory='High', character_class='Speed', is_captain=false where name='Blue Pianta';
update characters set slap_contact=55, charge_contact=35, slap_power=52, charge_power=82, bunting=20, run_speed=20, throwing_speed=80, fielding_stat=41, curveball_speed=132, fastball_speed=147, curve=20, stamina=67, star_boost_pct=50, hitting_trajectory='High', character_class='Speed', is_captain=false where name='Red Pianta';
update characters set slap_contact=55, charge_contact=35, slap_power=52, charge_power=82, bunting=20, run_speed=25, throwing_speed=80, fielding_stat=35, curveball_speed=132, fastball_speed=147, curve=20, stamina=67, star_boost_pct=50, hitting_trajectory='High', character_class='Speed', is_captain=false where name='Yellow Pianta';
update characters set slap_contact=60, charge_contact=40, slap_power=20, charge_power=40, bunting=40, run_speed=70, throwing_speed=40, fielding_stat=40, curveball_speed=116, fastball_speed=138, curve=58, stamina=42, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=false where name='Blue Noki';
update characters set slap_contact=60, charge_contact=40, slap_power=20, charge_power=40, bunting=40, run_speed=70, throwing_speed=40, fielding_stat=45, curveball_speed=120, fastball_speed=132, curve=49, stamina=42, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=false where name='Red Noki';
update characters set slap_contact=65, charge_contact=45, slap_power=25, charge_power=45, bunting=45, run_speed=70, throwing_speed=45, fielding_stat=40, curveball_speed=120, fastball_speed=132, curve=49, stamina=42, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=false where name='Green Noki';
update characters set slap_contact=65, charge_contact=45, slap_power=35, charge_power=55, bunting=37, run_speed=52, throwing_speed=55, fielding_stat=70, curveball_speed=120, fastball_speed=135, curve=35, stamina=55, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=false where name='Green Paratroopa';
update characters set slap_contact=70, charge_contact=50, slap_power=30, charge_power=50, bunting=30, run_speed=64, throwing_speed=40, fielding_stat=35, curveball_speed=126, fastball_speed=135, curve=55, stamina=56, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Red Koopa';
update characters set slap_contact=60, charge_contact=40, slap_power=30, charge_power=50, bunting=37, run_speed=52, throwing_speed=55, fielding_stat=70, curveball_speed=116, fastball_speed=138, curve=41, stamina=55, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=false where name='Paratroopa';
update characters set slap_contact=55, charge_contact=35, slap_power=30, charge_power=50, bunting=44, run_speed=45, throwing_speed=55, fielding_stat=70, curveball_speed=116, fastball_speed=135, curve=53, stamina=62, star_boost_pct=50, hitting_trajectory='Low', character_class='Technique', is_captain=false where name='Blue Shy Guy';
update characters set slap_contact=55, charge_contact=35, slap_power=30, charge_power=50, bunting=44, run_speed=55, throwing_speed=55, fielding_stat=70, curveball_speed=116, fastball_speed=130, curve=42, stamina=62, star_boost_pct=50, hitting_trajectory='Low', character_class='Technique', is_captain=false where name='Yellow Shy Guy';
update characters set slap_contact=60, charge_contact=40, slap_power=35, charge_power=55, bunting=44, run_speed=55, throwing_speed=55, fielding_stat=70, curveball_speed=116, fastball_speed=125, curve=40, stamina=62, star_boost_pct=50, hitting_trajectory='Low', character_class='Technique', is_captain=false where name='Green Shy Guy';
update characters set slap_contact=55, charge_contact=35, slap_power=30, charge_power=50, bunting=44, run_speed=45, throwing_speed=55, fielding_stat=75, curveball_speed=116, fastball_speed=130, curve=42, stamina=62, star_boost_pct=50, hitting_trajectory='Low', character_class='Technique', is_captain=false where name='Gray Shy Guy';
update characters set slap_contact=60, charge_contact=40, slap_power=45, charge_power=65, bunting=30, run_speed=70, throwing_speed=50, fielding_stat=30, curveball_speed=110, fastball_speed=138, curve=42, stamina=52, star_boost_pct=50, hitting_trajectory='High', character_class='Speed', is_captain=false where name='Blue Toad';
update characters set slap_contact=60, charge_contact=40, slap_power=45, charge_power=65, bunting=30, run_speed=70, throwing_speed=55, fielding_stat=35, curveball_speed=115, fastball_speed=130, curve=33, stamina=52, star_boost_pct=50, hitting_trajectory='High', character_class='Speed', is_captain=false where name='Yellow Toad';
update characters set slap_contact=55, charge_contact=35, slap_power=30, charge_power=50, bunting=30, run_speed=70, throwing_speed=55, fielding_stat=35, curveball_speed=110, fastball_speed=138, curve=42, stamina=52, star_boost_pct=50, hitting_trajectory='High', character_class='Speed', is_captain=false where name='Green Toad';
update characters set slap_contact=60, charge_contact=40, slap_power=45, charge_power=65, bunting=30, run_speed=70, throwing_speed=55, fielding_stat=25, curveball_speed=114, fastball_speed=140, curve=47, stamina=52, star_boost_pct=50, hitting_trajectory='High', character_class='Speed', is_captain=false where name='Purple Toad';
update characters set slap_contact=65, charge_contact=45, slap_power=30, charge_power=50, bunting=60, run_speed=70, throwing_speed=50, fielding_stat=55, curveball_speed=116, fastball_speed=138, curve=45, stamina=34, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Monty Mole';
update characters set slap_contact=60, charge_contact=45, slap_power=30, charge_power=45, bunting=35, run_speed=80, throwing_speed=40, fielding_stat=42, curveball_speed=116, fastball_speed=130, curve=35, stamina=60, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Red Yoshi';
update characters set slap_contact=50, charge_contact=40, slap_power=25, charge_power=35, bunting=35, run_speed=80, throwing_speed=35, fielding_stat=50, curveball_speed=126, fastball_speed=135, curve=45, stamina=60, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Blue Yoshi';
update characters set slap_contact=60, charge_contact=45, slap_power=30, charge_power=45, bunting=40, run_speed=75, throwing_speed=35, fielding_stat=50, curveball_speed=112, fastball_speed=130, curve=35, stamina=60, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Yellow Yoshi';
update characters set slap_contact=55, charge_contact=45, slap_power=30, charge_power=40, bunting=35, run_speed=80, throwing_speed=35, fielding_stat=50, curveball_speed=112, fastball_speed=130, curve=35, stamina=60, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Light-Blue Yoshi';
update characters set slap_contact=55, charge_contact=45, slap_power=30, charge_power=40, bunting=35, run_speed=85, throwing_speed=35, fielding_stat=50, curveball_speed=115, fastball_speed=127, curve=30, stamina=60, star_boost_pct=50, hitting_trajectory='Low', character_class='Speed', is_captain=false where name='Pink Yoshi';
update characters set slap_contact=65, charge_contact=45, slap_power=45, charge_power=65, bunting=40, run_speed=60, throwing_speed=60, fielding_stat=60, curveball_speed=130, fastball_speed=142, curve=50, stamina=75, star_boost_pct=50, hitting_trajectory='Low', character_class='Balanced', is_captain=false where name='Mii';
